<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sociatic Gutenverse Popup', 'sociatic' ),
	'categories' => array( 'sociatic-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/popup-builder {"elementId":"guten-LZXm1I","width":{"Desktop":{"point":"500","unit":"px"},"Tablet":{"point":"450","unit":"px"},"Mobile":{"point":"100","unit":"%"}},"containerPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":[],"Tablet":[]}},"backgroundColor":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0},"image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"custom"},"width":{"Desktop":{"unit":"%","point":"150"}}},"closeIcon":"gtn gtn-times-solid","closeButtonColor":{"Desktop":{"type":"variable","id":"theme-12"}},"closeButtonBgColor":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"closeButtonSize":{"Desktop":"20"},"closePositioningRight":{"Desktop":{"point":"25","unit":"px"}},"closePositioningTop":{"Desktop":{"point":"25","unit":"px"}},"closePadding":{"Desktop":[],"Tablet":[]},"closeBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]}},"closeButtonColorHover":{"Desktop":{"type":"variable","id":"theme-12"}},"closeBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]}}} -->
<div class="guten-element guten-popup-builder guten-LZXm1I" data-trigger="load" data-close-overlay="true"><div class="guten-popup guten-popup-center guten-popup-side-space"><div class="guten-popup-overlay"></div><div class="guten-popup-wrapper guten-popup-wrapper-center"><div class="guten-popup-content"><div class="guten-popup-close"><i class="gtn gtn-times-solid"></i></div><div class="guten-popup-container"><!-- wp:gutenverse/popup-container {"elementId":"guten-WU6hKm","position":"above"} -->
<div class="guten-element guten-popup-content-inner above"><div class="guten-popup-content-wrapper"><!-- wp:gutenverse/section {"gap":"no","elementId":"guten-J8s67B","background":{"type":"default","color":{"type":"variable","id":"theme-11"}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":3927,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/popup-bg.webp"},"Tablet":{"id":3927,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/popup-bg.webp"},"Mobile":{"id":3927,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/popup-bg.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"blendMode":{"Desktop":"normal"}},"opacity":"3000","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":[]}},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","bottom":"50","right":"40","left":"40"}},"Mobile":[]}} -->
<div class="section-wrapper" data-id="J8s67B"><section class="wp-block-gutenverse-section guten-element guten-section guten-J8s67B layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-1MhN9m","horizontalAlign":{"Desktop":"center","Tablet":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-1MhN9m"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="1MhN9m"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-EMCOvP","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"LzdbXD","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"34","unit":"px"},"Mobile":{"point":"28","unit":"px"},"Tablet":{"point":"28","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"294","unit":"px"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-EMCOvP">Try For Free &amp; Get Special Offer</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-FGh2tX","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"360","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-FGh2tX"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/form-builder {"elementId":"guten-21cBXD","successPadding":{"Desktop":[]},"successBorder":{"radius":{"Desktop":[]}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"30"}}},"padding":{"Desktop":[]}} -->
<form style="display:none" class="guten-element guten-form-builder guten-21cBXD"><!-- wp:gutenverse/form-input-email {"elementId":"guten-cHMTfv","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"100"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"boxShadow":{"horizontal":"0","vertical":"10","blur":"16","color":{"r":165,"g":62,"b":3,"a":0.1}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPlaceholder":"Enter Your Email Address","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"20","left":"30"}}},"inputMargin":{"Desktop":[]},"inputTypography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"none"}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-cHMTfv hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Enter Your Email Address" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-jxXne6","buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-0"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-10"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"showIcon":true,"icon":"fas fa-paper-plane","iconSize":{"Desktop":{"point":"16","unit":"px"}},"positioningType":{"Desktop":"inline"},"positioningLocation":"absolute","positioningRight":{"Desktop":{"point":"8","unit":"px"}},"positioningTop":{"Desktop":{"point":"8","unit":"px"}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"color":{"type":"variable","id":"white"},"iconColor":{"type":"variable","id":"white"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"18","left":"16"}}}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-jxXne6"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><i class="fa-lg fas fa-paper-plane"></i><span></span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></form>
<!-- /wp:gutenverse/form-builder --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/popup-container -->

<!-- wp:gutenverse/popup-container {"elementId":"guten-o494gJ","position":"bottom"} -->
<div class="guten-element guten-popup-content-inner bottom"><div class="guten-popup-content-wrapper"></div></div>
<!-- /wp:gutenverse/popup-container --></div></div></div></div></div>
<!-- /wp:gutenverse/popup-builder -->',
);
