<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sociatic Gutenverse Step To Grow', 'sociatic' ),
	'categories' => array( 'sociatic-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1190"},"gap":"no","elementId":"guten-SOrDlV","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"100","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":"80","right":"","bottom":"80","left":""}}}} -->
<div class="section-wrapper" data-id="SOrDlV"><section class="wp-block-gutenverse-section guten-element guten-section guten-SOrDlV layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-49inkG","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"bottom":"80"}},"Mobile":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"30"}},"Tablet":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-49inkG"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="49inkG"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-Z9rfdt","color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"oTRAFP","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"46","unit":"px"},"Mobile":{"point":"32","unit":"px"},"Tablet":{"point":"44","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"800"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"right":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-Z9rfdt animated guten-element-hide desktop-fadeInLeft">Easy Step To Get Start Grow Your Social Media</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-ds7jZ7","textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"80"}},"Tablet":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
<div class="guten-element gutenverse-text-editor guten-ds7jZ7 animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit. </p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-EaaSzu","content":"Contact Us","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"28","left":"28"}},"Mobile":[],"Tablet":[]},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-0"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-10"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}},"Tablet":[]},"all":{"type":"none"}},"buttonBorderHover":{"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"pnXC9z","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"}} -->
<div class="guten-element guten-button-wrapper guten-EaaSzu"><a class="guten-button animated guten-element-hide desktop-fadeInLeft guten-button-sm" href="#"><span>Contact Us</span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-Fr5BLO","margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"40"}},"Tablet":{"unit":"px","dimension":{"left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Fr5BLO"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Fr5BLO"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-2fh2W6","imgSrc":{"media":{"imageId":3985,"sizes":{"thumbnail":{"height":150,"width":9,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/line-9x150.webp","orientation":"portrait"},"medium":{"height":300,"width":3,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/line-3x300.webp","orientation":"portrait"},"large":{"height":1024,"width":9,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/line-9x1024.webp","orientation":"portrait"},"full":{"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/line.webp","height":1042,"width":9,"orientation":"portrait"}}},"size":"full"},"altOriginal":"","captionOriginal":"","width":{"Desktop":{"unit":"%","point":"5"}},"height":{"Desktop":{"point":"65","unit":"px"},"Tablet":{"point":"62","unit":"px"},"Mobile":{"point":"113","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"opacity":"0.4","imageFit":{"Desktop":"cover"},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal","delay":"400"},"hideDesktop":false,"hideMobile":true,"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"0"},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"30"},"Tablet":{"unit":"%","point":"6"},"Mobile":{"unit":"%","point":"12"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"56","unit":"px"},"Tablet":{"point":"12","unit":"px"},"Mobile":{"point":"8","unit":"px"}},"positioningTop":{"Desktop":{"point":"64","unit":"px"},"Mobile":{"point":"159","unit":"px"}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-2fh2W6 animated guten-element-hide desktop-fadeInDown hide-mobile"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/line.webp" height="1042" width="9"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/image {"elementId":"guten-aAQNCP","imgSrc":{"media":{"imageId":3985,"sizes":{"thumbnail":{"height":150,"width":9,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/line-9x150.webp","orientation":"portrait"},"medium":{"height":300,"width":3,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/line-3x300.webp","orientation":"portrait"},"large":{"height":1024,"width":9,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/line-9x1024.webp","orientation":"portrait"},"full":{"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/line.webp","height":1042,"width":9,"orientation":"portrait"}}},"size":"full"},"altOriginal":"","captionOriginal":"","width":{"Desktop":{"unit":"%","point":"5"}},"height":{"Desktop":{"point":"63","unit":"px"},"Tablet":{"point":"61","unit":"px"},"Mobile":{"point":"112","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"opacity":"0.4","imageFit":{"Desktop":"cover"},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal","delay":"600"},"hideDesktop":false,"hideMobile":true,"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"0"},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"30"},"Tablet":{"unit":"%","point":"6"},"Mobile":{"unit":"%","point":"12"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"56","unit":"px"},"Tablet":{"point":"12","unit":"px"},"Mobile":{"point":"8","unit":"px"}},"positioningRight":{"Tablet":{"point":"","unit":"px"}},"positioningTop":{"Desktop":{"point":"192","unit":"px"},"Tablet":{"point":"189","unit":"px"},"Mobile":{"point":"221","unit":"px"}},"positioningBottom":{"Tablet":{"point":"","unit":"px"}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-aAQNCP animated guten-element-hide desktop-fadeInDown hide-mobile"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/line.webp" height="1042" width="9"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-DNAlnj","title":"Book A Service","titleTag":"h3","description":"Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut","icon":"gtn gtn-smartphone2-light","iconSize":{"Desktop":"34","Tablet":"34","Mobile":"30"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"15","bottom":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}}},"iconColor":{"type":"variable","id":"theme-6"},"iconBgColor":{"type":"variable","id":"theme-5"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":[],"Mobile":[]}},"titlePadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"PaPuy7","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"right":"30"}}},"zIndex":{"Desktop":"0"},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal","delay":"300"}} -->
<div class="guten-element guten-DNAlnj animated guten-element-hide desktop-fadeInDown guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-smartphone2-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Book A Service</h3><p class="icon-box-description">Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-aQ7HO9","title":"Start Consultation","titleTag":"h3","description":"Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut","icon":"gtn gtn-Consultancy-light","iconSize":{"Desktop":"34","Tablet":"34","Mobile":"30"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"15","bottom":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}}},"iconColor":{"type":"variable","id":"theme-6"},"iconBgColor":{"type":"variable","id":"theme-5"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":[],"Mobile":[]}},"titlePadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"PaPuy7","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"0"}},"Tablet":{"unit":"px","dimension":{"right":"30"}}},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal","delay":"500"}} -->
<div class="guten-element guten-aQ7HO9 animated guten-element-hide desktop-fadeInDown guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-Consultancy-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Start Consultation</h3><p class="icon-box-description">Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-RB6wKQ","title":"Check Your Growth","titleTag":"h3","description":"Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut","icon":"gtn gtn-chart2-light","iconSize":{"Desktop":"34","Tablet":"34","Mobile":"30"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"15","bottom":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}}},"iconColor":{"type":"variable","id":"theme-6"},"iconBgColor":{"type":"variable","id":"theme-5"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":[],"Mobile":[]}},"titlePadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"PaPuy7","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"0"}},"Tablet":{"unit":"px","dimension":{"right":"30"}}},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal","delay":"700"}} -->
<div class="guten-element guten-RB6wKQ animated guten-element-hide desktop-fadeInDown guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-chart2-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Check Your Growth</h3><p class="icon-box-description">Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
