<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sociatic Gutenverse Business', 'sociatic' ),
	'categories' => array( 'sociatic-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1190"},"gap":"no","elementId":"guten-ilM0CW","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"100","top":"100"}},"Mobile":{"unit":"px","dimension":{"top":"80","bottom":"80"}}}} -->
<div class="section-wrapper" data-id="ilM0CW"><section class="wp-block-gutenverse-section guten-element guten-section guten-ilM0CW layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-RzjVcM"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-RzjVcM"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="RzjVcM"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-fztl4q","color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"oTRAFP","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"46","unit":"px"},"Mobile":{"point":"32","unit":"px"},"Tablet":{"point":"44","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"800"},"margin":{"Tablet":[],"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"right":"0"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-fztl4q animated guten-element-hide desktop-fadeInLeft">Everything You Need To Grow Your Business</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-2gUyP3","textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":{"unit":"px","dimension":{"bottom":"40"}},"Tablet":{"unit":"px","dimension":{"bottom":"20","right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"80"}},"Mobile":{"unit":"px","dimension":{"right":"20","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<div class="guten-element gutenverse-text-editor guten-2gUyP3 animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-jqTSJq","title":"Analytics Tracking","titleTag":"h4","description":"Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore.","icon":"gtn gtn-line-chart1-light","iconSize":{"Desktop":"36","Tablet":"34","Mobile":"30"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"containerBorder":{"radius":{"Desktop":[],"Tablet":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"15","bottom":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}}},"iconColor":{"type":"variable","id":"theme-6"},"iconBgColor":{"type":"variable","id":"theme-5"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":[],"Mobile":[]}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"PaPuy7","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"margin":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"120","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"0"}},"Tablet":{"unit":"px","dimension":{"right":"30"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
<div class="guten-element guten-jqTSJq animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-line-chart1-light"></i></div></div><div class="icon-box icon-box-body"><h4 class="title">Analytics Tracking</h4><p class="icon-box-description">Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore.</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-EaQITo","title":"Visual Report","titleTag":"h3","description":"Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore.","icon":"gtn gtn-graph-light","iconSize":{"Desktop":"36","Tablet":"34","Mobile":"32"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":[]},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":[],"Tablet":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"13","bottom":"15","left":"17"}},"Mobile":{"unit":"px","dimension":{"top":"12","right":"10","bottom":"12","left":"14"}},"Tablet":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"15","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}},"Tablet":[]},"iconColor":{"type":"variable","id":"theme-6"},"iconBgColor":{"type":"variable","id":"theme-5"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":[]}},"titlePadding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"PaPuy7","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"25","right":"","bottom":"","left":""}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"120","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"0"}},"Tablet":{"unit":"px","dimension":{"right":"30"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"500"}} -->
<div class="guten-element guten-EaQITo animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-graph-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Visual Report</h3><p class="icon-box-description">Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore.</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-vMfesy","title":"Research Prospect","titleTag":"h3","description":"Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore.","icon":"gtn gtn-search21-light","iconSize":{"Desktop":"36","Tablet":"34","Mobile":"32"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"containerBorder":{"radius":{"Desktop":[],"Tablet":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"15","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}}},"iconColor":{"type":"variable","id":"theme-6"},"iconBgColor":{"type":"variable","id":"theme-5"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":[]}},"titlePadding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"PaPuy7","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"25","right":"","bottom":"","left":""}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"120"}},"Mobile":{"unit":"px","dimension":{"right":"0"}},"Tablet":{"unit":"px","dimension":{"right":"30"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"700"}} -->
<div class="guten-element guten-vMfesy animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-search21-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Research Prospect</h3><p class="icon-box-description">Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-u0GMGO","background":{"type":"default","image":{"Desktop":{"id":3896,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/windows.webp"},"Tablet":{"id":3896,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/windows.webp"}},"position":{"Desktop":"bottom right","Tablet":"bottom center"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"size":{"Desktop":"custom","Tablet":"custom"},"width":{"Desktop":{"unit":"px","point":"500"},"Tablet":{"unit":"%","point":"65"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"},"hideMobile":true} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-u0GMGO animated guten-element-hide desktop-fadeInUp hide-mobile"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="u0GMGO"><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-yr414e","space":{"Desktop":{"point":"50","unit":"px"},"Tablet":{"point":"600","unit":"px"}},"border":{"radius":{"Tablet":[]}}} -->
<div class="guten-element guten-spacer guten-yr414e"></div>
<!-- /wp:gutenverse/spacer -->

<!-- wp:gutenverse/image {"elementId":"guten-EVQWp9","imgSrc":{"media":{"imageId":3898,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/growth-150x150.webp","orientation":"landscape"},"medium":{"height":298,"width":300,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/growth-300x298.webp","orientation":"landscape"},"large":{"height":1018,"width":1024,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/growth-1024x1018.webp","orientation":"landscape"},"full":{"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/growth.webp","height":1260,"width":1268,"orientation":"landscape"}}},"size":"full"},"altOriginal":"","captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":[]}},"imgShadow":{"horizontal":"0","vertical":"-7","blur":"32","color":{"r":165,"g":62,"b":3,"a":0.1}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"},"margin":{"Tablet":[]},"padding":{"Tablet":[]},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"35"},"Tablet":{"unit":"%","point":"30"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":"43"},"Tablet":{"unit":"%","point":"36"}},"positioningRight":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"positioningTop":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":"10"}},"positioningBottom":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-EVQWp9 animated guten-element-hide desktop-fadeInUp"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/growth.webp" height="1260" width="1268"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/image {"elementId":"guten-8ArYDs","imgSrc":{"media":{"imageId":3984,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/insight-150x150.webp","orientation":"landscape"},"medium":{"height":261,"width":300,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/insight-300x261.webp","orientation":"landscape"},"large":{"height":891,"width":1024,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/insight-1024x891.webp","orientation":"landscape"},"full":{"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/insight.webp","height":1290,"width":1482,"orientation":"landscape"}}},"size":"full"},"altOriginal":"","captionOriginal":"","width":{"Desktop":{"unit":"px","point":""}},"height":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":[]}},"imgShadow":{"color":{"r":165,"g":62,"b":3,"a":0.1},"horizontal":"15","vertical":"9","blur":"32"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"},"margin":{"Tablet":[],"Desktop":[]},"padding":{"Tablet":[],"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"40"},"Tablet":{"unit":"%","point":"35"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"positioningRight":{"Desktop":{"unit":"%","point":"-8"},"Tablet":{"unit":"%","point":"3"}},"positioningTop":{"Desktop":{"unit":"%","point":"55"},"Tablet":{"unit":"%","point":""}},"positioningBottom":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-8ArYDs animated guten-element-hide desktop-fadeInUp"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/insight.webp" height="1290" width="1482"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/image {"elementId":"guten-0juoWy","imgSrc":{"media":{"imageId":5780,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/likes-150x150.webp","orientation":"landscape"},"medium":{"height":239,"width":300,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/likes-300x239.webp","orientation":"landscape"},"full":{"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/likes.webp","height":332,"width":416,"orientation":"landscape"}}},"size":"full"},"altOriginal":"","captionOriginal":"","imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"imgShadow":{"color":{"r":165,"g":62,"b":3,"a":0.1},"horizontal":"-8","vertical":"10","blur":"30"},"align":{"Desktop":"left"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"40"},"Tablet":{"unit":"%","point":"36"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":"4"}},"positioningRight":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"positioningTop":{"Desktop":{"unit":"%","point":"55"},"Tablet":{"unit":"%","point":"61"}},"positioningBottom":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-0juoWy animated guten-element-hide desktop-fadeInUp"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/likes.webp" height="332" width="416"/></a></div>
<!-- /wp:gutenverse/image --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
