<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sociatic Gutenverse CEO', 'sociatic' ),
	'categories' => array( 'sociatic-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1190"},"gap":"no","elementId":"guten-XdjpI8","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"50","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"100","top":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"80","top":"50"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-H9Xek9","order":{"Tablet":2},"background":{"type":"default","image":{"Desktop":{"id":3896,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/windows.webp"},"Tablet":{"id":3896,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/windows.webp"},"Mobile":{"id":3896,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/windows.webp"}},"position":{"Desktop":"bottom left","Tablet":"bottom center","Mobile":"bottom center"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat","Mobile":"no-repeat"},"size":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"width":{"Desktop":{"point":"500","unit":"px"},"Mobile":{"point":"250","unit":"px"}}},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0"}},"Mobile":[]},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]}} -->
<!-- wp:gutenverse/image {"elementId":"guten-Xu2gg7","imgSrc":{"media":{"imageId":60,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/growth.webp","orientation":"landscape"},"medium":{"height":298,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/growth.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/growth.webp","height":354,"width":356,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"","captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"imgShadow":{"horizontal":"10","vertical":"9","blur":"30","color":{"r":165,"g":62,"b":3,"a":0.1}},"align":{"Desktop":null},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"},"hideMobile":true,"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"10"},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"30"},"Tablet":{"unit":"%","point":"25"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"positioningRight":{"Desktop":{"unit":"%","point":"5"},"Tablet":{"unit":"%","point":"6"}},"positioningTop":{"Desktop":{"unit":"%","point":"60"},"Tablet":{"unit":"%","point":""}},"positioningBottom":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/image {"elementId":"guten-JHeN1T","imgSrc":{"media":{"imageId":61,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_6NYVPE6NEB.webp","orientation":"landscape"},"medium":{"height":300,"width":216,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_6NYVPE6NEB.webp","orientation":"portrait"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_6NYVPE6NEB.webp","height":556,"width":400,"orientation":"portrait"}}},"size":"full"},"altType":"original","altOriginal":"businessman play tablet device","captionOriginal":"","width":{"Desktop":{"point":"400","unit":"px"},"Mobile":{"point":"200","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-7","left":"-50"}},"Tablet":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":[],"Tablet":[]},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/image {"elementId":"guten-eoOngH","imgSrc":{"media":{"imageId":62,"sizes":{"thumbnail":{"height":140,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/engagement.webp","orientation":"landscape"},"medium":{"height":126,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/engagement.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/engagement.webp","height":140,"width":334,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"engagement funfact","captionOriginal":"","imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":[]}},"imgShadow":{"color":{"r":165,"g":62,"b":3,"a":0.1},"horizontal":"-8","vertical":"11","blur":"30","position":"outline"},"align":{"Desktop":"left"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"},"hideMobile":true,"border":{"radius":{"Desktop":[]}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"32"},"Tablet":{"unit":"%","point":"24"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":"-8"},"Tablet":{"unit":"%","point":"4"}},"positioningRight":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"positioningTop":{"Desktop":{"unit":"%","point":"42"},"Tablet":{"unit":"%","point":""}},"positioningBottom":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"imageLoad":"lazy"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-menFWN","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"40"}},"Tablet":{"unit":"px","dimension":{"left":"0","top":"","bottom":"50"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"50"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0"}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-Yduo4A","content":"The Right Decision For Your Marketing Strategy","color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"46","unit":"px"},"Mobile":{"point":"32","unit":"px"},"Tablet":{"point":"44","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"800"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"20","top":""}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-fHHXa1","textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur Excepteur sint occaecat cupidatat non proident.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1190"},"isChild":true,"gap":"no","elementId":"guten-kudDPX","margin":{"Mobile":[],"Desktop":[]},"padding":{"Mobile":[],"Desktop":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":44,"Mobile":null,"Tablet":36},"elementId":"guten-kAOhpt","verticalAlign":{"Desktop":"center","Tablet":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"20"}},"Desktop":[]},"padding":{"Mobile":[],"Desktop":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"}} -->
<!-- wp:gutenverse/image {"elementId":"guten-pTEeB5","imgSrc":{"media":{"imageId":10,"sizes":{"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/ceo.webp","height":116,"width":116,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"ceo image","captionOriginal":"","width":{"Mobile":{"unit":"%","point":""},"Desktop":{"point":"58","unit":"px"}},"height":{"Desktop":{"point":"58","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"%","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}},"Tablet":[],"Mobile":[]}},"align":{"Mobile":"left"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":[]},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"unit":"%","point":"46"}},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-rUEKAw","titleTag":"h3","text":"Hugo Baron","focusText":"","subText":"CEO and Co-Founder","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"800"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":[],"Tablet":[]},"mainPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":[],"Tablet":[]},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"focusPadding":{"Desktop":[]},"subColor":{"type":"variable","id":"gv-color-text-secondary"},"subTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"subMargin":{"Desktop":{"unit":"px","dimension":{"top":""}}},"subPadding":{"Desktop":[]},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":56,"Tablet":null,"Mobile":null},"elementId":"guten-BUMlR2","verticalAlign":{"Desktop":"center","Tablet":"center"},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/button {"elementId":"guten-ABrgvO","content":"More About Us","url":"#","alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"36","left":"36"}},"Mobile":[],"Tablet":[]},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-primary"}},"buttonBackgroundHover":{"type":"default","gradientColor":[{"color":"rgba(152, 109, 248, 1)","opacity":1,"id":1,"offset":"0.000","active":true},{"color":"rgb(126, 32, 207)","id":2,"offset":"1.000","active":false}],"color":{"type":"variable","id":"gv-color-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}},"all":{"type":"none","width":"1","color":{"r":152,"g":109,"b":248,"a":1}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"700"},"color":{"type":"variable","id":"white"},"iconColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"positioningType":{"Desktop":"inline"},"ariaLabel":"about us"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
