<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sociatic Gutenverse Strategy', 'sociatic' ),
	'categories' => array( 'sociatic-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1190"},"gap":"no","elementId":"guten-vSSJhh","background":{"type":"default","color":{"type":"variable","id":"white"}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"80","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"50","right":"20","bottom":"0"}}}} -->
<div class="section-wrapper" data-id="vSSJhh"><section class="wp-block-gutenverse-section guten-element guten-section guten-vSSJhh layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-jLarl2","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"left":"","bottom":"30"}},"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"left":"","right":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"50"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-jLarl2"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="jLarl2"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-egcPpZ","color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"oTRAFP","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"46","unit":"px"},"Mobile":{"point":"32","unit":"px"},"Tablet":{"point":"44","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"800"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"bottom":""}},"Mobile":[]},"padding":{"Desktop":[],"Tablet":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-egcPpZ animated guten-element-hide desktop-fadeInLeft">Create A Social Media Strategy That Works</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-00Ii7v","textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"0","bottom":"30"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"80"}},"Mobile":{"unit":"px","dimension":{"right":"20","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"},"positioningType":{"Tablet":"custom"},"positioningWidth":{"Tablet":{"point":"671","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-00Ii7v animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-vnAPky","title":"Profesional Team","titleTag":"h4","description":"Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore.","icon":"gtn gtn-badge","iconSize":{"Desktop":"36","Tablet":"34","Mobile":"30"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"containerBorder":{"radius":{"Desktop":[],"Tablet":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"15","bottom":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}}},"iconColor":{"type":"variable","id":"theme-6"},"iconBgColor":{"type":"variable","id":"theme-5"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":[],"Mobile":[]}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"PaPuy7","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"margin":{"Desktop":[],"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"120","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"50","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
<div class="guten-element guten-vnAPky animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-badge"></i></div></div><div class="icon-box icon-box-body"><h4 class="title">Profesional Team</h4><p class="icon-box-description">Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore.</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-EhnfN0","title":"Target Oriented","titleTag":"h4","description":"Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore.","icon":"gtn gtn-Target-light","iconSize":{"Desktop":"36","Tablet":"34","Mobile":"32"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"15","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}}},"iconColor":{"type":"variable","id":"theme-6"},"iconBgColor":{"type":"variable","id":"theme-5"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":[]}},"titlePadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"PaPuy7","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"35","right":"","bottom":"","left":""}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"120","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"0"}},"Tablet":{"unit":"px","dimension":{"right":"50"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"500"}} -->
<div class="guten-element guten-EhnfN0 animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-Target-light"></i></div></div><div class="icon-box icon-box-body"><h4 class="title">Target Oriented</h4><p class="icon-box-description">Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore.</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-NIYCEK","title":"Succes Guarantee","titleTag":"h4","description":"Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore.","icon":"gtn gtn-rocket-light","iconSize":{"Desktop":"36","Tablet":"34","Mobile":"32"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"containerBorder":{"radius":{"Desktop":[],"Tablet":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"15","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}}},"iconColor":{"type":"variable","id":"theme-6"},"iconBgColor":{"type":"variable","id":"theme-5"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":[]}},"titlePadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"PaPuy7","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"35","right":"","bottom":"","left":""}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"120"}},"Mobile":{"unit":"px","dimension":{"right":"0"}},"Tablet":{"unit":"px","dimension":{"right":"50"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"700"}} -->
<div class="guten-element guten-NIYCEK animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-rocket-light"></i></div></div><div class="icon-box icon-box-body"><h4 class="title">Succes Guarantee</h4><p class="icon-box-description">Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-6kkc8M","background":{"type":"default","image":{"Desktop":{"id":3896,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/windows.webp"},"Tablet":{"id":3896,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/windows.webp"}},"position":{"Desktop":"bottom right","Mobile":"bottom center","Tablet":"bottom center"},"repeat":{"Desktop":"no-repeat","Mobile":"no-repeat","Tablet":"no-repeat"},"size":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"width":{"Desktop":{"unit":"px","point":"480"},"Tablet":{"unit":"px","point":"420"},"Mobile":{"unit":"%","point":"84"}}},"verticalAlign":{"Desktop":"flex-start"},"margin":{"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"40"}},"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"80"}},"Mobile":[],"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp","Tablet":"none"},"duration":"normal"},"hideMobile":true} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-6kkc8M animated guten-element-hide desktop-fadeInUp hide-mobile"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="6kkc8M"><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-ILF2qh","space":{"Desktop":{"point":"50","unit":"px"},"Tablet":{"point":"450","unit":"px"}}} -->
<div class="guten-element guten-spacer guten-ILF2qh"></div>
<!-- /wp:gutenverse/spacer -->

<!-- wp:gutenverse/image {"elementId":"guten-fsbXSa","imgSrc":{"media":{"imageId":3908,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/Analityc-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":297,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/Analityc-297x300.webp","orientation":"portrait"},"large":{"height":1024,"width":1012,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/Analityc-1012x1024.webp","orientation":"portrait"},"full":{"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/Analityc.webp","height":1315,"width":1300,"orientation":"portrait"}}},"size":"full"},"altOriginal":"","captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":[]}},"imgShadow":{"color":{"r":165,"g":62,"b":3,"a":0.1},"horizontal":"0","vertical":"-7","blur":"32"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"},"hideMobile":true,"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"40"},"Tablet":{"unit":"%","point":"28"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":"42"},"Tablet":{"unit":"%","point":"37"}},"positioningRight":{"Tablet":{"unit":"%","point":""},"Desktop":{"unit":"%","point":""}},"positioningTop":{"Tablet":{"unit":"%","point":"12"},"Desktop":{"unit":"%","point":""}},"positioningBottom":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-fsbXSa animated guten-element-hide desktop-fadeInUp hide-mobile"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/Analityc.webp" height="1315" width="1300"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/image {"elementId":"guten-4cOpNR","imgSrc":{"media":{"imageId":4992,"sizes":{"thumbnail":{"height":140,"width":150,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/user-reserch-150x140.webp","orientation":"landscape"},"medium":{"height":133,"width":300,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/user-reserch-300x133.webp","orientation":"landscape"},"full":{"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/user-reserch.webp","height":140,"width":316,"orientation":"landscape"}}},"size":"full"},"altOriginal":"","captionOriginal":"","imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":[]}},"imgShadow":{"horizontal":"8","vertical":"15","blur":"30","position":"outline","color":{"r":165,"g":62,"b":3,"a":0.1}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"32"},"Tablet":{"unit":"%","point":"25"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"positioningRight":{"Desktop":{"unit":"%","point":"-10"},"Tablet":{"unit":"%","point":"7"}},"positioningTop":{"Desktop":{"unit":"%","point":"58"},"Tablet":{"unit":"%","point":"62"}},"positioningBottom":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-4cOpNR animated guten-element-hide desktop-fadeInUp"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/user-reserch.webp" height="140" width="316"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/image {"elementId":"guten-rZ6KBE","imgSrc":{"media":{"imageId":5780,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/likes-150x150.webp","orientation":"landscape"},"medium":{"height":239,"width":300,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/likes-300x239.webp","orientation":"landscape"},"full":{"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/likes.webp","height":332,"width":416,"orientation":"landscape"}}},"size":"full"},"altOriginal":"","captionOriginal":"","imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":[]}},"imgShadow":{"color":{"r":165,"g":62,"b":3,"a":0.1},"horizontal":"-8","vertical":"11","blur":"30","position":"outline"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"40"},"Tablet":{"unit":"%","point":"30"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":"2"},"Tablet":{"unit":"%","point":"7"}},"positioningRight":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"positioningTop":{"Desktop":{"unit":"%","point":"57"},"Tablet":{"unit":"%","point":"62"}},"positioningBottom":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-rZ6KBE animated guten-element-hide desktop-fadeInUp"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/likes.webp" height="332" width="416"/></a></div>
<!-- /wp:gutenverse/image --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
