<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sociatic Gutenverse 404', 'sociatic' ),
	'categories' => array( 'sociatic-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1190"},"gap":"no","elementId":"guten-19yBLX","background":{"type":"default","color":{"type":"variable","id":"theme-11"}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":3883,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/404-bg.webp"},"Tablet":{"id":3883,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/404-bg.webp"},"Mobile":{"id":3883,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/404-bg.webp"}},"position":{"Desktop":"center center","Mobile":"custom"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"xposition":{"Mobile":{"unit":"%","point":"40"}},"yposition":{"Mobile":{"unit":"%","point":""}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-100"}},"Tablet":{"unit":"px","dimension":{"top":"-180"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"280","bottom":"230"}},"Tablet":{"unit":"px","dimension":{"top":"320","bottom":"225"}},"Mobile":{"unit":"px","dimension":{"top":"320","bottom":"250","right":"20","left":"20"}}}} -->
<div class="section-wrapper" data-id="19yBLX"><section class="wp-block-gutenverse-section guten-element guten-section guten-19yBLX layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-173A2v"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-173A2v"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="173A2v"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-wHXHwP","type":1,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"MeJ5ER","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Mobile":{"point":"92","unit":"px"},"Tablet":{"point":"116","unit":"px"},"Desktop":{"point":"136","unit":"px"}},"weight":"800"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":""}},"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"},"advanceAnimation":{"type":"page","actions":[]}} -->
<div class="guten-data"><div data-var="adanimAttrswHXHwP" data-value="{&quot;blockType&quot;:&quot;heading&quot;,&quot;advanceAnimation&quot;:{&quot;type&quot;:&quot;page&quot;,&quot;actions&quot;:[]}}"></div></div><h1 class="wp-block-gutenverse-heading guten-element guten-wHXHwP animated guten-element-hide desktop-fadeInUp" data-id="wHXHwP">404</h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-NAcgD9","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"oTRAFP","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"46","unit":"px"},"Mobile":{"point":"32","unit":"px"},"Tablet":{"point":"44","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"800"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"},"advanceAnimation":{"actions":[],"loadOn":"hover"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-NAcgD9 animated guten-element-hide desktop-fadeInUp">Page Not Found</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"width":{"Desktop":"400"},"isChild":true,"gap":"no","elementId":"guten-nrCJed","margin":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}}} -->
<div class="section-wrapper" data-id="nrCJed"><section class="wp-block-gutenverse-section guten-element guten-section guten-nrCJed layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-Cd76DZ"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Cd76DZ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Cd76DZ"><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-CGYI2v","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"margin":{"Tablet":[],"Mobile":[],"Desktop":[]},"padding":{"Tablet":[],"Mobile":[],"Desktop":{"unit":"%","dimension":{"right":"","left":""}}},"positioningType":{"Desktop":"default","Tablet":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"64"},"Tablet":{"point":"1000","unit":"px"},"Mobile":{"unit":"%","point":"90"}}} -->
<div class="guten-element gutenverse-text-editor guten-CGYI2v"><div class="text-content-inner"><!-- wp:paragraph -->
<p>The page you are looking for might have been removed had its name changed or is temporarily unavailable</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"680"},"isChild":true,"elementId":"guten-V0kFo0"} -->
<div class="section-wrapper" data-id="V0kFo0"><section class="wp-block-gutenverse-section guten-element guten-section guten-V0kFo0 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-J2lHuY","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-J2lHuY"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="J2lHuY"><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-efROVK","alignment":{"Desktop":null},"positioningType":{"Desktop":"default"}} -->
<div class="guten-element gutenverse-text-editor guten-efROVK"><div class="text-content-inner"><!-- wp:search {"label":"Search","showLabel":false,"width":100,"widthUnit":"%","buttonText":"Search","style":{"border":{"radius":"50px","width":"1px"},"color":{"background":"#986df8"},"typography":{"fontSize":"14px","fontStyle":"normal","fontWeight":"400","lineHeight":"2"}},"borderColor":"theme-13","textColor":"white","fontFamily":"mulish"} /--></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
