<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sociatic Gutenverse 404', 'sociatic' ),
	'categories' => array( 'sociatic-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1190"},"gap":"no","elementId":"guten-19yBLX","background":{"type":"default","color":{"type":"variable","id":"gv-color-background-primary"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":3883,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/404-bg.webp"},"Tablet":{"id":3883,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/404-bg.webp"},"Mobile":{"id":3883,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/404-bg.webp"}},"position":{"Desktop":"center center","Mobile":"custom"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"xposition":{"Mobile":{"unit":"%","point":"40"}},"yposition":{"Mobile":{"unit":"%","point":""}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-100"}},"Tablet":{"unit":"px","dimension":{"top":"-180"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"280","bottom":"230"}},"Tablet":{"unit":"px","dimension":{"top":"320","bottom":"225"}},"Mobile":{"unit":"px","dimension":{"top":"320","bottom":"250","right":"20","left":"20"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-173A2v"} -->
<!-- wp:gutenverse/heading {"elementId":"guten-kuASPs","content":"404","type":1,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-accent"},"typography":{"type":"variable","id":"gv-font-heading-404","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Mobile":{"point":"92","unit":"px"},"Tablet":{"point":"116","unit":"px"},"Desktop":{"point":"136","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.1"}}},"containsAnchorTag":false,"margin":{"Desktop":[]},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-NAcgD9","content":"Page Not Found","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"46","unit":"px"},"Mobile":{"point":"32","unit":"px"},"Tablet":{"point":"44","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"800"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"200"},"advanceAnimation":{"actions":[],"loadOn":"hover"}} /-->

<!-- wp:gutenverse/section {"width":{"Desktop":"400"},"isChild":true,"gap":"no","elementId":"guten-sadqad","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-zWv8zr"} -->
<!-- wp:gutenverse/text-editor {"elementId":"guten-XxwmB0","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"containsAnchorTag":false} -->
<!-- wp:paragraph -->
<p>The page you are looking for might have been removed had its name changed or is temporarily unavailable</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/search {"elementId":"guten-44RMkR","buttonWidth":{"Desktop":{"point":"","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-text-placeholder"}},"inputPlaceholder":"Search here...","inputPadding":{"Desktop":{"unit":"px","dimension":{"right":"22","left":"22"}},"Mobile":[]},"inputMargin":{"Desktop":{"unit":"px","dimension":{"right":"15"}},"Mobile":{"unit":"px","dimension":{"right":"0","bottom":"10"}}},"inputHeight":{"Desktop":"54"},"inputWidth":{"Desktop":{"unit":"%","point":"45"},"Mobile":{"unit":"%","point":"100"}},"inputTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-border"}}},"inputBorderNormalResponsive":{"Mobile":{"radius":[]}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"gv-color-white"}},"alignContent":{"Desktop":"center"},"closeIconType":"svg","closeIconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik04IDI0LjY2N2MtMC4xNzEgMC0wLjM0MS0wLjA2NS0wLjQ3MS0wLjE5Ni0wLjI2LTAuMjYtMC4yNi0wLjY4MyAwLTAuOTQzbDE2LTE2YzAuMjYtMC4yNiAwLjY4My0wLjI2IDAuOTQzIDBzMC4yNiAwLjY4MyAwIDAuOTQzbC0xNiAxNmMtMC4xMzEgMC4xMzEtMC4zMDEgMC4xOTYtMC40NzIgMC4xOTZ6TTI0IDI0LjY2N2MtMC4xNzEgMC0wLjM0MS0wLjA2NS0wLjQ3MS0wLjE5NmwtMTYtMTZjLTAuMjYtMC4yNi0wLjI2LTAuNjgzIDAtMC45NDNzMC42ODMtMC4yNiAwLjk0MyAwbDE2IDE2YzAuMjYgMC4yNiAwLjI2IDAuNjgzIDAgMC45NDMtMC4xMzEgMC4xMzEtMC4zMDEgMC4xOTYtMC40NzIgMC4xOTZ6Ij48L3BhdGg+Cjwvc3ZnPgo="} -->
<!-- wp:gutenverse/button {"elementId":"guten-dmKScD","role":"submit","content":"Search","buttonSize":"xs","buttonWidth":{"Desktop":"100"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"right":"35","left":"35"}},"Mobile":[]},"buttonBackground":{"color":{"type":"variable","id":"gv-color-primary"},"type":"default"},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"hoverTextColor":{"type":"variable","id":"white"}} /-->
<!-- /wp:gutenverse/search -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
