<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sociatic Gutenverse Pricing', 'sociatic' ),
	'categories' => array( 'sociatic-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1190","Tablet":""},"gap":"no","elementId":"guten-BgaclZ","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"120","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"100","top":"0"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","top":"0","bottom":"80"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-aOx6y2","horizontalAlign":{"Desktop":"default","Tablet":"center"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-khF1fp","content":"Pricing Plans For Every Need","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"46","unit":"px"},"Mobile":{"point":"32","unit":"px"},"Tablet":{"point":"44","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"800"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"","left":"","top":"","bottom":""}},"Tablet":{"unit":"%","dimension":{"right":"0","left":"0","top":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-X6L5Ry","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"28","left":"28","top":"","bottom":""}},"Tablet":{"unit":"%","dimension":{"right":"15","left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet consectetur adipiscing elit semper dalar elementum tempus hac tellus libero accumsan dolor sit amet consctur.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-1R37Bj","margin":{"Desktop":{"unit":"px","dimension":{"top":"60"}}},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":33.3,"Tablet":50,"Mobile":null},"elementId":"guten-daLnJA","background":{"type":"default","color":{"type":"variable","id":"gv-color-background-primary"},"fixed":{"Desktop":false}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":3948,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/pricing-bg-orange.webp"},"Tablet":{"id":3948,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/pricing-bg-orange.webp"}},"position":{"Desktop":"center center","Tablet":"center center"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"size":{"Desktop":"custom","Tablet":"cover"},"width":{"Desktop":{"unit":"%","point":"145"}}},"opacity":"1","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"all":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"left":"0","right":"20","bottom":"20"}},"Mobile":{"unit":"px","dimension":{"right":"0","bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-XbGEVF","content":"Basic","type":3,"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"34","unit":"px"},"Mobile":{"point":"28","unit":"px"},"Tablet":{"point":"28","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"containsAnchorTag":false,"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}}},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-Iruo9j","titleTag":"h3","text":"$39","focusText":" /month","subText":"Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-primary-alt","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"56","unit":"px"},"Mobile":{"point":"36","unit":"px"},"Tablet":{"point":"44","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"800"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"focusColor":{"type":"variable","id":"gv-color-text-secondary"},"focusTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"focusMargin":{"Desktop":[],"Tablet":[]},"focusPadding":{"Desktop":[],"Tablet":[]},"subColor":{"type":"variable","id":"gv-color-text-secondary"},"subTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"subMargin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":""}}},"subPadding":{"Desktop":[],"Mobile":[]},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"10"}}}} /-->

<!-- wp:gutenverse/divider {"elementId":"guten-sJVXFi","width":{"Desktop":"100"},"dividerColor":{"r":238,"g":223,"b":215,"a":0.64},"size":{"Desktop":"1.5"},"gap":{"Desktop":"20"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/icon-list {"elementId":"guten-P1Wspa","spaceBetween":{"Desktop":"10"},"iconColor":{"type":"variable","id":"gv-color-accent"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"textIndent":{"Desktop":"15"},"textTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-AHIjEA","ariaLabel":"3  Social profiles","iconType":"svg","text":"3  Social profiles"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-lJikp5","ariaLabel":"12 Team members","iconType":"svg","text":"12 Team members"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-rJX9wn","ariaLabel":"5 Competitors per profile","iconType":"svg","text":"5 Competitors per profile"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-QW3YwA","ariaLabel":"Hashtags per profile","iconType":"svg","text":"Hashtags per profile"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-bJ1gwZ","ariaLabel":"Free Platform Access","iconType":"svg","text":"Free Platform Access"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-rOk722","ariaLabel":"Monthly Target","iconType":"svg","text":"Monthly Target"} /-->
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/button {"elementId":"guten-wDHni5","content":"Get Started","url":"#","buttonWidth":{"Desktop":"100"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"36","left":"36"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-primary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}},"all":{"type":"none","width":"1","color":{"r":152,"g":109,"b":248,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"white"},"iconColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"positioningType":{"Desktop":"default"},"ariaLabel":"get basic price"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.3,"Tablet":100},"elementId":"guten-FV33M1","order":{"Tablet":3},"background":{"type":"default","color":{"type":"variable","id":"gv-color-primary"}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":3949,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/pricing-bg-purple.webp"},"Tablet":{"id":3949,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/pricing-bg-purple.webp"},"Mobile":{"id":3949,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/pricing-bg-purple.webp"}},"position":{"Desktop":"center center","Tablet":"center center"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"size":{"Desktop":"custom","Tablet":"cover"},"width":{"Desktop":{"unit":"%","point":"145"}}},"opacity":"0.2","horizontalAlign":{"Desktop":"default","Tablet":"center"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20","left":"0"}},"Tablet":{"unit":"%","dimension":{"left":"26","right":"26","bottom":""}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"10","bottom":"10","right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"50","left":"40"}},"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-H3K0Vx","content":"Premium","type":3,"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"34","unit":"px"},"Mobile":{"point":"28","unit":"px"},"Tablet":{"point":"28","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-wDUJT3","titleTag":"h3","text":"$49","focusText":" /month","subText":"Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"white"},"mainTypography":{"type":"variable","id":"gv-font-primary-alt","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"56","unit":"px"},"Mobile":{"point":"36","unit":"px"},"Tablet":{"point":"44","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"800"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":[]},"mainPadding":{"Desktop":[],"Tablet":[]},"focusColor":{"type":"variable","id":"white"},"focusTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"focusMargin":{"Desktop":[],"Tablet":[]},"focusPadding":{"Desktop":[],"Tablet":[]},"subColor":{"type":"variable","id":"white"},"subTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"subMargin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}},"Tablet":[]},"subPadding":{"Desktop":[],"Tablet":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"10","right":"","left":""}}}} /-->

<!-- wp:gutenverse/divider {"elementId":"guten-dIqIgW","width":{"Desktop":"100"},"dividerColor":{"r":131,"g":93,"b":207,"a":0.47},"size":{"Desktop":"1.5"},"gap":{"Desktop":"20"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/icon-list {"elementId":"guten-R7FjaF","spaceBetween":{"Desktop":"10"},"iconColor":{"type":"variable","id":"white"},"textColor":{"type":"variable","id":"white"},"textIndent":{"Desktop":"15"},"textTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-aADcUX","ariaLabel":"3  Social profiles","iconType":"svg","text":"3  Social profiles"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-Au6tbG","ariaLabel":"12 Team members","iconType":"svg","text":"12 Team members"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-4jfGAX","ariaLabel":"5 Competitors per profile","iconType":"svg","text":"5 Competitors per profile"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-IiHqMI","ariaLabel":"Hashtags per profile","iconType":"svg","text":"Hashtags per profile"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-Il9XwA","ariaLabel":"Free Platform Access","iconType":"svg","text":"Free Platform Access"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-q56kyd","ariaLabel":"Monthly Target","iconType":"svg","text":"Monthly Target"} /-->
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/button {"elementId":"guten-7bFnnW","content":"Get Started","url":"#","buttonWidth":{"Desktop":"100"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"36","left":"36"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"white"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-text-primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}},"all":{"type":"none","width":"1","color":{"r":152,"g":109,"b":248,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"gv-color-primary"},"iconColor":{"type":"variable","id":"gv-color-primary"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"hoverTextColor":{"type":"variable","id":"white"},"positioningType":{"Desktop":"default"},"ariaLabel":"get premium price"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.3,"Tablet":50,"Mobile":null},"elementId":"guten-266nmF","background":{"type":"default","color":{"type":"variable","id":"gv-color-background-primary"}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":3948,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/pricing-bg-orange.webp"},"Tablet":{"id":3948,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/pricing-bg-orange.webp"}},"position":{"Desktop":"center center","Tablet":"center center"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"size":{"Desktop":"custom","Tablet":"cover"},"width":{"Desktop":{"unit":"%","point":"145"}},"blendMode":{"Desktop":"normal"}},"opacity":"1","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"all":{"type":"none"}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Tablet":{"unit":"px","dimension":{"left":"","right":"","top":"","bottom":"20"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","top":"10","bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"50","left":"40"}},"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"700"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-iOU0DK","content":"Standard","type":3,"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"34","unit":"px"},"Mobile":{"point":"28","unit":"px"},"Tablet":{"point":"28","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-BWB8qw","titleTag":"h3","text":"$29","focusText":" /month","subText":"Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-primary-alt","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"56","unit":"px"},"Mobile":{"point":"36","unit":"px"},"Tablet":{"point":"44","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"800"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":[]},"mainPadding":{"Desktop":[],"Tablet":[]},"focusColor":{"type":"variable","id":"gv-color-text-secondary"},"focusTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"focusMargin":{"Desktop":[],"Tablet":[]},"focusPadding":{"Desktop":[],"Tablet":[]},"subColor":{"type":"variable","id":"gv-color-text-secondary"},"subTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"subMargin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"subPadding":{"Desktop":[]},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"10"}}}} /-->

<!-- wp:gutenverse/divider {"elementId":"guten-PVNnsM","width":{"Desktop":"100"},"dividerColor":{"r":238,"g":223,"b":215,"a":0.64},"size":{"Desktop":"1.5"},"gap":{"Desktop":"20"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/icon-list {"elementId":"guten-7rW339","spaceBetween":{"Desktop":"10"},"iconColor":{"type":"variable","id":"gv-color-accent"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"textIndent":{"Desktop":"15"},"textTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-OUdL2E","ariaLabel":"3  Social profiles","iconType":"svg","text":"3  Social profiles"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-KK9SvJ","ariaLabel":"12 Team members","iconType":"svg","text":"12 Team members"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-ZHfVVV","ariaLabel":"5 Competitors per profile","iconType":"svg","text":"5 Competitors per profile"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-sDZVof","ariaLabel":"Hashtags per profile","iconType":"svg","text":"Hashtags per profile"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-iObZbZ","ariaLabel":"Free Platform Access","iconType":"svg","text":"Free Platform Access"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-oNQTbl","ariaLabel":"Monthly Target","iconType":"svg","text":"Monthly Target"} /-->
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/button {"elementId":"guten-XTQkMV","content":"Get Started","url":"#","buttonWidth":{"Desktop":"100"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"36","left":"36"}},"Tablet":[]},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-primary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}},"all":{"type":"none","width":"1","color":{"r":152,"g":109,"b":248,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"white"},"iconColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"positioningType":{"Desktop":"default"},"ariaLabel":"get standard price"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
