<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sociatic Gutenverse Popup', 'sociatic' ),
	'categories' => array( 'sociatic-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/popup-builder {"elementId":"guten-LZXm1I","width":{"Desktop":{"point":"500","unit":"px"},"Tablet":{"point":"450","unit":"px"},"Mobile":{"point":"100","unit":"%"}},"maxHeight":{"Desktop":{"unit":"vh"}},"containerPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":[],"Tablet":[]}},"backgroundColor":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0},"image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"custom"},"width":{"Desktop":{"unit":"%","point":"150"}}},"closeIcon":"gtn gtn-times-solid","closeIconType":"svg","closeIconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik03LjIxOSA1Ljc4MWwtMS40MzggMS40MzggOC43ODEgOC43ODEtOC43ODEgOC43ODEgMS40MzggMS40MzggOC43ODEtOC43ODEgOC43ODEgOC43ODEgMS40MzgtMS40MzgtOC43ODEtOC43ODEgOC43ODEtOC43ODEtMS40MzgtMS40MzgtOC43ODEgOC43ODF6Ij48L3BhdGg+Cjwvc3ZnPgo=","closeButtonColor":{"Desktop":{"type":"variable","id":"theme-12"}},"closeButtonBgColor":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"closeButtonSize":{"Desktop":"20"},"closePositioningLeft":{"Desktop":{"unit":"px"}},"closePositioningRight":{"Desktop":{"point":"25","unit":"px"}},"closePositioningTop":{"Desktop":{"point":"25","unit":"px"}},"closePositioningBottom":{"Desktop":{"unit":"px"}},"closePadding":{"Desktop":[],"Tablet":[]},"closeBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]}},"closeButtonColorHover":{"Desktop":{"type":"variable","id":"theme-12"}},"closeBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]}},"openWaitTime":5000} -->
<!-- wp:gutenverse/popup-container {"elementId":"guten-WU6hKm","position":"above"} -->
<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-J8s67B","background":{"type":"default","color":{"type":"variable","id":"gv-color-background-primary"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":3927,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/popup-bg.webp"},"Tablet":{"id":3927,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/popup-bg.webp"},"Mobile":{"id":3927,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/popup-bg.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"blendMode":{"Desktop":"normal"}},"opacity":"3000","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":[]}},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","bottom":"50","right":"40","left":"40"}},"Mobile":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-1MhN9m","horizontalAlign":{"Desktop":"center","Tablet":"center"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-EMCOvP","content":"Try For Free \u0026 Get Special Offer","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"34","unit":"px"},"Mobile":{"point":"28","unit":"px"},"Tablet":{"point":"28","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"containsAnchorTag":false,"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"294","unit":"px"}}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-FGh2tX","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"containsAnchorTag":false,"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"360","unit":"px"}}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/form-builder {"elementId":"guten-21cBXD","formId":{"label":"Newsletter Form","value":1041},"successPadding":{"Desktop":[]},"successBorder":{"radius":{"Desktop":[]}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"30"}}},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/form-input-email {"elementId":"guten-cHMTfv","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"100"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"boxShadow":{"horizontal":"0","vertical":"10","blur":"16","color":{"r":165,"g":62,"b":3,"a":0.1}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPlaceholder":"Enter Your Email Address","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"20","left":"30"}}},"inputMargin":{"Desktop":[]},"inputTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"none"}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} /-->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-jxXne6","buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-primary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"showIcon":true,"icon":"fas fa-paper-plane","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTQ5OC4xIDUuNmMxMC4xIDcgMTUuNCAxOS4xIDEzLjUgMzEuMmwtNjQgNDE2Yy0xLjUgOS43LTcuNCAxOC4yLTE2IDIzcy0xOC45IDUuNC0yOCAxLjZMMjg0IDQyNy43bC02OC41IDc0LjFjLTguOSA5LjctMjIuOSAxMi45LTM1LjIgOC4xUzE2MCA0OTMuMiAxNjAgNDgwVjM5Ni40YzAtNCAxLjUtNy44IDQuMi0xMC43TDMzMS44IDIwMi44YzUuOC02LjMgNS42LTE2LS40LTIycy0xNS43LTYuNC0yMi0uN0wxMDYgMzYwLjggMTcuNyAzMTYuNkM3LjEgMzExLjMgLjMgMzAwLjcgMCAyODguOXM1LjktMjIuOCAxNi4xLTI4LjdsNDQ4LTI1NmMxMC43LTYuMSAyMy45LTUuNSAzNCAxLjR6Ii8+PC9zdmc+","iconSize":{"Desktop":{"point":"16","unit":"px"}},"positioningType":{"Desktop":"inline"},"positioningLocation":"absolute","positioningRight":{"Desktop":{"point":"8","unit":"px"}},"positioningTop":{"Desktop":{"point":"5","unit":"px"}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"color":{"type":"variable","id":"white"},"iconColor":{"type":"variable","id":"white"},"ariaLabel":"submit newsletter","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"18","left":"16"}}},"iconLineHeight":true} /-->
<!-- /wp:gutenverse/form-builder -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/popup-container -->

<!-- wp:gutenverse/popup-container {"elementId":"guten-o494gJ","position":"bottom"} /-->
<!-- /wp:gutenverse/popup-builder -->',
	'is_sync' => false,
);
