<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sociatic Gutenverse Footer', 'sociatic' ),
	'categories' => array( 'sociatic-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1190"},"gap":"no","elementId":"guten-AahUF3","background":{"type":"default","color":{"type":"variable","id":"theme-1"}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"40"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"50","bottom":"50"}}},"className":"#footer"} -->
<div class="section-wrapper" data-id="AahUF3"><section class="wp-block-gutenverse-section guten-element guten-section guten-AahUF3 layout-boxed align-stretch #footer"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-w0cGtK"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-w0cGtK"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="w0cGtK"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"width":{"Desktop":"1190"},"isChild":true,"gap":"no","elementId":"guten-FB4VCC","background":{"type":"default","color":""},"margin":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="section-wrapper" data-id="FB4VCC"><section class="wp-block-gutenverse-section guten-element guten-section guten-FB4VCC layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":34.4,"Tablet":100},"elementId":"guten-NisvJG","verticalAlign":{"Desktop":"center"},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-NisvJG"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="NisvJG"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-V5BZib","imgSrc":{"media":{"imageId":3892,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/Logo-white-150x150.webp","orientation":"landscape"},"medium":{"height":69,"width":300,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/Logo-white-300x69.webp","orientation":"landscape"},"large":{"height":234,"width":1024,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/Logo-white-1024x234.webp","orientation":"landscape"},"full":{"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/Logo-white.webp","height":281,"width":1230,"orientation":"landscape"}}},"size":"full"},"altOriginal":"","captionOriginal":"","width":{"Desktop":{"unit":"px","point":""},"Mobile":{"unit":"px","point":""},"Tablet":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"","unit":"px"}},"url":"#","imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"align":{"Desktop":"left"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Tablet":{"unit":"%","point":"24"},"Desktop":{"unit":"%","point":"50"},"Mobile":{"unit":"%","point":"50"}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-V5BZib"><a class="guten-image-wrapper" href="#"><img class="gutenverse-image-box-filled" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/Logo-white.webp" height="281" width="1230"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-Q4W04x","textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"20","right":""}},"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"317","unit":"px"},"Tablet":{"unit":"%","point":"100"}}} -->
<div class="guten-element gutenverse-text-editor guten-Q4W04x"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/social-icons {"elementId":"guten-K0oA8G","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"16"},"alignment":{"Desktop":"flex-start"},"shape":"square","iconColor":{"type":"variable","id":"white"},"bgColor":{"type":"variable","id":"theme-6"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"itemPadding":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"hoverIconColor":{"type":"variable","id":"theme-0"},"hoverBgColor":{"type":"variable","id":"white"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="guten-element guten-social-icons guten-K0oA8G square horizontal fill"><!-- wp:gutenverse/social-icon {"elementId":"guten-MgZQV8"} -->
<div class="guten-element guten-social-icon guten-MgZQV8 facebook"><a id="guten-MgZQV8" href="#"><i class="gtn gtn-facebook-f"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-BemfJl"} -->
<div class="guten-element guten-social-icon guten-BemfJl instagram"><a id="guten-BemfJl" href="#"><i class="fab fa-instagram"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-UEOoQs"} -->
<div class="guten-element guten-social-icon guten-UEOoQs twitter"><a id="guten-UEOoQs" href="#"><i class="fab fa-twitter"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-22hdUN"} -->
<div class="guten-element guten-social-icon guten-22hdUN link"><a id="guten-22hdUN" href="#"><i class="gtn gtn-linkedin-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":34.1,"Tablet":50},"elementId":"guten-0VMoAn","verticalAlign":{"Desktop":"center","Tablet":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"30"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-0VMoAn"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="0VMoAn"><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-list {"elementId":"guten-1VTsbg","spaceBetween":{"Desktop":"10"},"iconColor":{"type":"variable","id":"theme-6"},"iconSize":{"Desktop":"15"},"textColor":{"type":"variable","id":"white"},"textIndent":{"Desktop":"10"},"textTypography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}}}} -->
<div class="guten-element guten-icon-list guten-1VTsbg"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-Rwp0Ug"} -->
<div class="guten-element guten-icon-list-item guten-Rwp0Ug"><a id="guten-Rwp0Ug"><i class="fas fa-envelope"></i><span class="list-text ">example@example.com</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-iXrhEO"} -->
<div class="guten-element guten-icon-list-item guten-iXrhEO"><a id="guten-iXrhEO"><i class="fas fa-phone-alt"></i><span class="list-text ">+62 4321-234-11</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":31.5,"Tablet":50},"elementId":"guten-rZ10h3","verticalAlign":{"Desktop":"center"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}},"Desktop":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-rZ10h3"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="rZ10h3"><div class="guten-column-wrapper"><!-- wp:gutenverse/form-builder {"elementId":"guten-NuqsCM","formId":{"label":"Form Message","value":6284},"successAlign":{"Desktop":null},"successPadding":{"Desktop":[]},"successBorder":{"radius":{"Desktop":[]}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"15"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<form style="display:none" class="guten-element guten-form-builder guten-NuqsCM" data-form-id="6284"><!-- wp:gutenverse/form-input-email {"elementId":"guten-Hi6mqo","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":[],"Mobile":[]},"labelMargin":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"100"}},"positioningLocation":"default","margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"inputPlaceholder":"Email Address","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"20","left":"30"}},"Mobile":[],"Tablet":[]},"inputMargin":{"Desktop":[],"Mobile":[]},"inputTypography":{"font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Mobile":{"point":"14","unit":"px"},"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}},"Mobile":[],"Tablet":[]},"all":{"type":"none"}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"none"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"none"}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}},"inputBgColorHover":{"Desktop":{"type":"variable","id":"white"}},"inputBgColorFocus":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-Hi6mqo hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Email Address" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-CW6Lk0","content":"Get Started","buttonWidth":{"Mobile":"100","Tablet":""},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-0"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-10"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"positioningType":{"Desktop":"inline","Mobile":"full","Tablet":"inline"},"positioningWidth":{"Tablet":{"unit":"%","point":"100"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"point":"","unit":"px"},"Tablet":{"unit":"px","point":""},"Mobile":{"unit":"%","point":""}},"positioningRight":{"Desktop":{"unit":"%","point":"2"},"Mobile":{"unit":"%","point":"0"}},"positioningTop":{"Desktop":{"unit":"%","point":"11"},"Tablet":{"unit":"%","point":""},"Mobile":{"unit":"%","point":"120"}},"positioningBottom":{"Mobile":{"unit":"%","point":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"color":{"type":"variable","id":"white"},"typography":{"font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"weight":"500","lineHeight":{"Desktop":{"unit":"em","point":""}},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"15","unit":"px"}}},"alignButton":{"Desktop":"flex-end","Mobile":"flex-start"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"28","left":"28"}},"Tablet":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}}}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-CW6Lk0"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Get Started</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></form>
<!-- /wp:gutenverse/form-builder --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-AF6peW","margin":{"Desktop":{"unit":"px","dimension":{"top":"80"}},"Mobile":{"unit":"px","dimension":{"top":"100"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="section-wrapper" data-id="AF6peW"><section class="wp-block-gutenverse-section guten-element guten-section guten-AF6peW layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-Y8JKMA","margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Y8JKMA"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Y8JKMA"><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-n4d6jo","alignment":{"Desktop":"left","Tablet":"left","Mobile":"center"},"textColor":{"type":"variable","id":"white"},"typography":{"font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Mobile":{"unit":"px","dimension":{"bottom":"0"}}}} -->
<div class="guten-element gutenverse-text-editor guten-n4d6jo"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Copyright © 2023. All rights reserved.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-07yIJV"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-07yIJV"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="07yIJV"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-pB2up6"} -->
<div class="section-wrapper" data-id="pB2up6"><section class="wp-block-gutenverse-section guten-element guten-section guten-pB2up6 layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":70,"Tablet":60,"Mobile":null},"elementId":"guten-qDCEnG","margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-qDCEnG"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="qDCEnG"><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-9ObXPy","alignment":{"Desktop":"right","Mobile":"center"},"textColor":{"type":"variable","id":"white"},"typography":{"font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"margin":{"Mobile":[],"Desktop":[]},"padding":{"Mobile":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Desktop":[]}} -->
<div class="guten-element gutenverse-text-editor guten-9ObXPy"><div class="text-content-inner"><!-- wp:paragraph {"style":{"elements":{"link":{"color":{"text":"var:preset|color|white"}}}}} -->
<p class="has-link-color"><a href="#">Privacy Policy</a></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":30,"Tablet":40,"Mobile":null},"elementId":"guten-Nox5DC","margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Nox5DC"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Nox5DC"><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-xIjnRT","alignment":{"Desktop":"right","Mobile":"center"},"textColor":{"type":"variable","id":"white"},"typography":{"font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"}} -->
<div class="guten-element gutenverse-text-editor guten-xIjnRT"><div class="text-content-inner"><!-- wp:paragraph {"style":{"elements":{"link":{"color":{"text":"var:preset|color|white"}}}}} -->
<p class="has-link-color"><a href="#">Terms and conditions</a></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
