<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sociatic Gutenverse About', 'sociatic' ),
	'categories' => array( 'sociatic-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1190"},"gap":"no","elementId":"guten-iyVgZX","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"50","top":"80"}},"Mobile":{"unit":"px","dimension":{"bottom":"80","top":"50"}}}} -->
<div class="section-wrapper" data-id="iyVgZX"><section class="wp-block-gutenverse-section guten-element guten-section guten-iyVgZX layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-1cvdRv","order":{"Tablet":2},"background":{"type":"default","image":{"Desktop":{"id":3896,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/windows.webp"},"Tablet":{"id":3896,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/windows.webp"},"Mobile":{"id":3896,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/windows.webp"}},"position":{"Desktop":"bottom left","Tablet":"bottom center","Mobile":"bottom center"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat","Mobile":"no-repeat"},"size":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"width":{"Desktop":{"point":"500","unit":"px"},"Mobile":{"point":"250","unit":"px"}}},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0"}},"Mobile":[]},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-1cvdRv"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="1cvdRv"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-7Ec9tR","imgSrc":{"media":{"imageId":3898,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/growth-150x150.webp","orientation":"landscape"},"medium":{"height":298,"width":300,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/growth-300x298.webp","orientation":"landscape"},"large":{"height":1018,"width":1024,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/growth-1024x1018.webp","orientation":"landscape"},"full":{"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/growth.webp","height":1260,"width":1268,"orientation":"landscape"}}},"size":"full"},"altOriginal":"","captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"imgShadow":{"horizontal":"10","vertical":"9","blur":"30","color":{"r":165,"g":62,"b":3,"a":0.1}},"align":{"Desktop":null},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"},"hideMobile":true,"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"10"},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"30"},"Tablet":{"unit":"%","point":"25"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"positioningRight":{"Desktop":{"unit":"%","point":"5"},"Tablet":{"unit":"%","point":"6"}},"positioningTop":{"Desktop":{"unit":"%","point":"60"},"Tablet":{"unit":"%","point":""}},"positioningBottom":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-7Ec9tR animated guten-element-hide desktop-fadeInUp hide-mobile"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/growth.webp" height="1260" width="1268"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/image {"elementId":"guten-mCVXNL","imgSrc":{"media":{"imageId":3897,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/StockSnap_6NYVPE6NEB-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":216,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/StockSnap_6NYVPE6NEB-216x300.webp","orientation":"portrait"},"full":{"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/StockSnap_6NYVPE6NEB.webp","height":556,"width":400,"orientation":"portrait"}}},"size":"full"},"altOriginal":"","captionOriginal":"","width":{"Desktop":{"point":"400","unit":"px"},"Mobile":{"point":"200","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-7","left":"-50"}},"Tablet":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":[],"Tablet":[]}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-mCVXNL"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/StockSnap_6NYVPE6NEB.webp" height="556" width="400"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/image {"elementId":"guten-eoOngH","imgSrc":{"media":{"imageId":5779,"sizes":{"thumbnail":{"height":140,"width":150,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/engagement-150x140.webp","orientation":"landscape"},"medium":{"height":126,"width":300,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/engagement-300x126.webp","orientation":"landscape"},"full":{"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/engagement.webp","height":140,"width":334,"orientation":"landscape"}}},"size":"full"},"altOriginal":"","captionOriginal":"","imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Tablet":[]}},"imgShadow":{"color":{"r":165,"g":62,"b":3,"a":0.1},"horizontal":"-8","vertical":"11","blur":"30","position":"outline"},"align":{"Desktop":"left"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"},"hideMobile":true,"border":{"radius":{"Desktop":[]}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"32"},"Tablet":{"unit":"%","point":"24"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":"-8"},"Tablet":{"unit":"%","point":"4"}},"positioningRight":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"positioningTop":{"Desktop":{"unit":"%","point":"42"},"Tablet":{"unit":"%","point":""}},"positioningBottom":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-eoOngH animated guten-element-hide desktop-fadeInUp hide-mobile"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/engagement.webp" height="140" width="334"/></a></div>
<!-- /wp:gutenverse/image --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-GrNcTV","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"40"}},"Tablet":{"unit":"px","dimension":{"left":"0","top":"","bottom":"50"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-GrNcTV"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="GrNcTV"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-bZsYop","color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"oTRAFP","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"46","unit":"px"},"Mobile":{"point":"32","unit":"px"},"Tablet":{"point":"44","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"800"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"20","top":""}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-bZsYop animated guten-element-hide desktop-fadeInRight">The Right Decision For Your Marketing Strategy</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-HPCcye","textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
<div class="guten-element gutenverse-text-editor guten-HPCcye animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur Excepteur sint occaecat cupidatat non proident.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-n07z1l","textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
<div class="guten-element gutenverse-text-editor guten-n07z1l animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium totam rem aperiam eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
