<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sociatic Gutenverse Single Content', 'sociatic' ),
	'categories' => array( 'sociatic-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1190"},"gap":"no","elementId":"guten-jwbM6s","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"120"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"80","top":"80"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","top":"50","bottom":"50"}}}} -->
<div class="section-wrapper" data-id="jwbM6s"><section class="wp-block-gutenverse-section guten-element guten-section guten-jwbM6s layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":65,"Tablet":100},"elementId":"guten-0WMIz1"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-0WMIz1"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="0WMIz1"><div class="guten-column-wrapper"><!-- wp:gutenverse/post-featured-image {"elementId":"guten-M1UvmZ","imageBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-post-featured-image guten-M1UvmZ"></div>
<!-- /wp:gutenverse/post-featured-image -->

<!-- wp:gutenverse/post-content {"elementId":"guten-jT5jWc","typography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"color":{"type":"variable","id":"theme-2"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Mobile":[]}} -->
<div class="guten-element guten-post-content guten-jT5jWc"></div>
<!-- /wp:gutenverse/post-content -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-iKsGvQ","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"bottom":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-13"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Mobile":[]}} -->
<div class="section-wrapper" data-id="iKsGvQ"><section class="wp-block-gutenverse-section guten-element guten-section guten-iKsGvQ layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"elementId":"guten-BA5rhi","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-BA5rhi"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="BA5rhi"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-HwcCcm","type":4,"color":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"K0QhlR","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.7"}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"10","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"positioningType":{"Desktop":"inline"}} -->
<h4 class="wp-block-gutenverse-heading guten-element guten-HwcCcm">Category :</h4>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/post-terms {"elementId":"guten-tLae0f","linkTo":"term","typography":{"font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"17","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":""}}},"color":{"type":"variable","id":"theme-10"},"colorHover":{"type":"variable","id":"theme-2"},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-post-terms guten-tLae0f"></div>
<!-- /wp:gutenverse/post-terms --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-d28trz","horizontalAlign":{"Desktop":"flex-end"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-d28trz"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="d28trz"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-yqQJ1v"} -->
<div class="section-wrapper" data-id="yqQJ1v"><section class="wp-block-gutenverse-section guten-element guten-section guten-yqQJ1v layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":60,"Mobile":40,"Tablet":null},"elementId":"guten-ZpLACU","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"flex-end","Mobile":"flex-start","Tablet":"flex-end"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ZpLACU"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ZpLACU"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-NVtvem","type":4,"color":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"K0QhlR","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.7"}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"5"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"0","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"positioningType":{"Desktop":"inline"}} -->
<h4 class="wp-block-gutenverse-heading guten-element guten-NVtvem">Share This :</h4>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":40,"Mobile":60},"elementId":"guten-oGOpmO","verticalAlign":{"Desktop":"center"},"margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"left":"","top":"0"}},"Desktop":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-oGOpmO"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="oGOpmO"><div class="guten-column-wrapper"><!-- wp:gutenverse/social-share {"elementId":"guten-TiNoi5","iconColor":{"type":"variable","id":"white"},"iconBackgroundColor":{"type":"variable","id":"theme-6"},"borderType":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"iconColorHover":{"type":"variable","id":"white"},"iconBackgroundColorHover":{"type":"variable","id":"theme-0"},"borderTypeHover":{"radius":{"Desktop":[]}},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"alignment":{"Desktop":"flex-end","Mobile":"flex-start"},"gap":{"Desktop":"12"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"positioningType":{"Desktop":"default"}} -->
<div class="guten-element guten-social-share guten-TiNoi5 horizontal guten-social-share"><!-- wp:gutenverse/social-share-facebook {"elementId":"guten-L7B8lE","showText":false} /-->

<!-- wp:gutenverse/social-share-linkedin {"elementId":"guten-ZoWEDv","showText":false} /-->

<!-- wp:gutenverse/social-share-twitter {"elementId":"guten-tTBMTr","showText":false} /--></div>
<!-- /wp:gutenverse/social-share --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/post-comment {"elementId":"guten-IGixt1","typographyHeading":{"type":"variable","id":"PaPuy7","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"typographyText":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"typographyLink":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"typographyLabel":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"colorHeading":{"type":"variable","id":"theme-1"},"colorText":{"type":"variable","id":"theme-2"},"colorLink":{"type":"variable","id":"theme-0"},"colorLabel":{"type":"variable","id":"theme-1"},"marginHeading":{"Desktop":[],"Mobile":[]},"marginText":{"Desktop":{"unit":"px","dimension":{"top":"10"}}},"marginLink":{"Desktop":{"unit":"px","dimension":{"right":"5"}}},"marginLabel":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}},"Mobile":[]},"inputBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-13"}}},"typographyButton":{"type":"variable","id":"pnXC9z","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"marginButton":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"20"}}},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Tablet":[],"Mobile":[]},"colorButton":{"type":"variable","id":"white"},"bgcolorButton":{"type":"variable","id":"theme-0"},"borderButton":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}},"Tablet":[],"Mobile":[]}},"colorButtonHover":{"type":"variable","id":"white"},"bgcolorButtonHover":{"type":"variable","id":"theme-10"},"borderButtonHover":{"radius":{"Desktop":[]}},"marginButtonHover":{"Desktop":[]},"paddingButtonHover":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="guten-element guten-post-comment guten-IGixt1"></div>
<!-- /wp:gutenverse/post-comment --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":35,"Tablet":100,"Mobile":null},"elementId":"guten-ftyYDE","margin":{"Desktop":{"unit":"px","dimension":{"left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"50","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ftyYDE"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ftyYDE"><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-d9GpUg"} -->
<div class="section-wrapper" data-id="d9GpUg"><section class="wp-block-gutenverse-section guten-element guten-section guten-d9GpUg layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-O4PGjW","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"boxShadow":{"color":{"r":165,"g":62,"b":3,"a":0.1},"horizontal":"0","vertical":"1","blur":"35"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"30","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"20","left":"30"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-O4PGjW"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="O4PGjW"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-V8oNM8","type":4,"color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"PaPuy7","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<h4 class="wp-block-gutenverse-heading guten-element guten-V8oNM8">Popular Post</h4>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/post-list {"elementId":"guten-wkEIjF","numberPost":"3","metaEnabled":true,"metaDateEnabled":true,"metaPosition":"bottom","contentMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"contentPadding":{"Desktop":[]},"contentWidth":{"Desktop":{"point":"","unit":"px"}},"contentBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[]},"titleColor":{"type":"variable","id":"theme-1"},"titleTypography":{"type":"variable","id":"K0QhlR","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.7"}}},"titleColorHover":{"type":"variable","id":"theme-0"},"imageMargin":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconRadius":{"Desktop":[]},"metaTypography":{"type":"variable","id":"1Tn02D","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1"}}},"metaIconSize":{"Desktop":"12"},"metaIconSpacing":{"Desktop":"6"},"metaMargin":{"Desktop":{"unit":"px","dimension":{"top":"5"}}},"metaPadding":{"Desktop":[]},"metaColor":{"type":"variable","id":"theme-14"},"metaBorder":{"radius":{"Desktop":[]}},"metaHoverBorder":{"radius":{"Desktop":[]}},"paginationMargin":{"Desktop":[]},"paginationPadding":{"Desktop":[]},"paginationBorder":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-post-list guten-wkEIjF"></div>
<!-- /wp:gutenverse/post-list --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-9fT3Ee"} -->
<div class="section-wrapper" data-id="9fT3Ee"><section class="wp-block-gutenverse-section guten-element guten-section guten-9fT3Ee layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-aYg8Xj","background":{"type":"default","color":{"type":"variable","id":"theme-11"}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":3927,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/popup-bg.webp"},"Tablet":{"id":3927,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/popup-bg.webp"},"Mobile":{"id":3927,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/popup-bg.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-aYg8Xj"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="aYg8Xj"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-mevrQH","type":5,"color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"rhlJXQ","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"800"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-mevrQH">Weekly Newsletter</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-m6LLxq","textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"border":{"radius":{"Desktop":[]}},"margin":{"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":""}},"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Tablet":[],"Mobile":[],"Desktop":[]},"positioningType":{"Desktop":"full","Tablet":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"unit":"%","point":"64"},"Tablet":{"point":"1000","unit":"px"},"Mobile":{"unit":"%","point":"90"}}} -->
<div class="guten-element gutenverse-text-editor guten-m6LLxq"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit Ut elit tellus, luctus nec.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/form-builder {"elementId":"guten-o8USW0","formId":{"label":"Subscribe Form","value":2977},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<form style="display:none" class="guten-element guten-form-builder guten-o8USW0" data-form-id="2977"><!-- wp:gutenverse/form-input-email {"elementId":"guten-drOiAE","showLabel":false,"showHelper":false,"labelPadding":{"Mobile":[],"Desktop":[]},"labelMargin":{"Mobile":[],"Desktop":[]},"helperPadding":{"Desktop":[]},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"100"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"inputPlaceholder":"Email Address","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"40","bottom":"18","left":"40"}},"Mobile":[],"Tablet":[]},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[],"Tablet":[]},"inputTypography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-1"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}},"Mobile":[],"Tablet":[]},"all":{"type":"none"}},"inputBorderHover":{"radius":{"Desktop":[]}},"inputBorderFocus":{"radius":{"Desktop":[]}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-drOiAE hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Email Address" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-MZw0Yh","content":"Subscribe","buttonWidth":{"Mobile":"100","Desktop":"100","Tablet":"100"},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-10"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-0"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}},"Tablet":[]}},"icon":"fas fa-paper-plane","iconSize":{"Desktop":{"point":"16","unit":"px"}},"positioningType":{"Desktop":"default","Mobile":"full","Tablet":"custom"},"positioningLocation":"default","positioningRight":{"Desktop":{"point":"8","unit":"px"},"Tablet":{"point":"8","unit":"px"},"Mobile":{"point":"0","unit":"px"}},"positioningTop":{"Mobile":{"point":"80","unit":"px"},"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"}},"positioningBottom":{"Mobile":{"point":"","unit":"px"}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"color":{"type":"variable","id":"white"},"iconColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"pnXC9z","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"28","left":"28"}},"Mobile":[],"Tablet":[]}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-MZw0Yh"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Subscribe</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></form>
<!-- /wp:gutenverse/form-builder --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
