<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sociatic Gutenverse Brand Logo', 'sociatic' ),
	'categories' => array( 'sociatic-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1190"},"gap":"no","elementId":"guten-KX5HL4","margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","bottom":"20"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"50","bottom":"50"}},"Mobile":{"unit":"px","dimension":{"top":"30","bottom":"0"}}}} -->
<div class="section-wrapper" data-id="KX5HL4"><section class="wp-block-gutenverse-section guten-element guten-section guten-KX5HL4 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":22.6,"Tablet":30},"elementId":"guten-p3yPbw","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-p3yPbw"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="p3yPbw"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-aNU9qy","type":4,"textAlign":{"Mobile":"center","Tablet":"left"},"color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"PaPuy7","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","bottom":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"right":"40"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":[]},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"227","unit":"px"}}} -->
<h4 class="wp-block-gutenverse-heading guten-element guten-aNU9qy">Some of brand we work with</h4>
<!-- /wp:gutenverse/heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":77.4,"Tablet":70},"elementId":"guten-nsJ0tP","verticalAlign":{"Desktop":"center","Tablet":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-nsJ0tP"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="nsJ0tP"><div class="guten-column-wrapper"><!-- wp:gutenverse/logo-slider {"elementId":"guten-FJGTsU","logos":[{"title":"One","_key":"cUiwME","src":{"id":3814,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/financio.webp"}},{"title":"Two","_key":"VV8lwF","src":{"id":3815,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/echelon.webp"}},{"title":"Four","_key":"tM7z30","src":{"id":3816,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/nettiz.webp"}},{"title":"Three","_key":"lDZVBQ","src":{"id":3817,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/zever.webp"}}],"imagePadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"20","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"imageMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"imageHoverPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"20","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"imageHoverMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"imageBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"imageBorderHover":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"spacing":{"Desktop":"0"},"itemShowed":{"Desktop":"4","Tablet":"3","Mobile":"2"},"autoplay":true,"loop":true,"arrowPadding":{"Desktop":[]},"arrowMargin":{"Desktop":[]},"arrowBorder":{"radius":{"Desktop":[]}},"opacity":"0.8","hoverOpacity":"1","margin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Mobile":[]}} -->
<div class="guten-element guten-client-logo grid-desktop-3 guten-FJGTsU arrow-bottom-edge"><div class="client-list"><div id="guten-FJGTsU" class="swiper-container" data-loop="true" data-autoplay="true" data-timeout="2400" data-nav="false" data-arrow="false" data-breakpoints="{&quot;0&quot;:{&quot;spaceBetween&quot;:10,&quot;slidesPerView&quot;:2},&quot;768&quot;:{&quot;spaceBetween&quot;:10,&quot;slidesPerView&quot;:3},&quot;1024&quot;:{&quot;spaceBetween&quot;:0,&quot;slidesPerView&quot;:4}}"><div class="swiper-wrapper"><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/financio.webp" alt="One"/><img class="hover-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/financio.webp" alt="One"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/echelon.webp" alt="Two"/><img class="hover-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/echelon.webp" alt="Two"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/nettiz.webp" alt="Four"/><img class="hover-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/nettiz.webp" alt="Four"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/zever.webp" alt="Three"/><img class="hover-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/zever.webp" alt="Three"/></div></div></div></div></div></div>
<!-- /wp:gutenverse/logo-slider --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
