<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sociatic Gutenverse Home Hero', 'sociatic' ),
	'categories' => array( 'sociatic-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1190"},"gap":"no","elementId":"guten-yFKL9K","background":{"type":"default","color":{"type":"variable","id":"theme-11"}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":3944,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/bg-hero.webp"},"Tablet":{"id":3944,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/bg-hero.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"opacity":"0.6","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"150"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"150","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"bottom":"80"}}}} -->
<div class="section-wrapper" data-id="yFKL9K"><section class="wp-block-gutenverse-section guten-element guten-section guten-yFKL9K layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-yhXZPK","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-yhXZPK"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="yhXZPK"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-6sqq8L","type":1,"textAlign":{"Tablet":"left"},"color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"uiccB6","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"66","unit":"px"},"Tablet":{"point":"74","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"800"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"150","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0"}},"Mobile":[]},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-6sqq8L animated guten-element-hide desktop-fadeInLeft">The Best Solution For Your Social Media Strategies</h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-XfLCFN","alignment":{"Tablet":"left"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"CfBlR9","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":""}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"0"}},"Tablet":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"},"positioningType":{"Desktop":"custom","Tablet":"default","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"420","unit":"px"},"Mobile":{"point":"","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-XfLCFN animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-sUtZ0b"} -->
<div class="section-wrapper" data-id="sUtZ0b"><section class="wp-block-gutenverse-section guten-element guten-section guten-sUtZ0b layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-5YHjwQ","margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-5YHjwQ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="5YHjwQ"><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-vikC9K","content":"Learn More","url":"#","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"36","left":"36"}},"Mobile":[]},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-0"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-10"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}},"all":{"type":"none"}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"pnXC9z","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"hoverTextColor":{"type":"variable","id":"white"},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-button-wrapper guten-vikC9K"><a class="guten-button animated guten-element-hide desktop-fadeInLeft guten-button-sm" href="#"><span>Learn More</span></a></div>
<!-- /wp:gutenverse/button -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-BloPLB","url":"#","title":"","description":"","icon":"gtn gtn-play","iconSize":{"Desktop":"18"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"17","right":"15","bottom":"17","left":"19"}}},"iconMargin":{"Desktop":[]},"iconColor":{"type":"variable","id":"theme-0"},"iconHoverColor":{"type":"variable","id":"white"},"iconBgColor":{"type":"variable","id":"white"},"iconHoverBgColor":{"type":"variable","id":"theme-0"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"47","right":"47","bottom":"47","left":"47"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-0"}}},"iconBorderHover":{"radius":{"Desktop":[]},"all":{"color":{"type":"variable","id":"theme-0"}}},"titlePadding":{"Desktop":[]},"titleMargin":{"Desktop":[]},"descMargin":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-BloPLB animated guten-element-hide desktop-fadeInLeft guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><a class="" href="#"><i class="gtn gtn-play"></i></a></div></div><div class="icon-box icon-box-body"><a class="" href="#"><h2 class="title"></h2></a><p class="icon-box-description"></p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-WPHXgl","background":{"type":"default","image":{"Desktop":{"id":3896,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/windows.webp"},"Tablet":{"id":3896,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/windows.webp"},"Mobile":{"id":3896,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/windows.webp"}},"position":{"Desktop":"bottom right","Tablet":"bottom center","Mobile":"bottom center"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat","Mobile":"no-repeat"},"size":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"width":{"Desktop":{"unit":"px","point":"480"},"Tablet":{"unit":"px","point":"480"},"Mobile":{"unit":"px","point":"200"}},"fixed":{"Desktop":false,"Tablet":false}},"verticalAlign":{"Desktop":"flex-end"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"40"}},"Tablet":[],"Desktop":[]},"padding":{"Mobile":[],"Tablet":[],"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-WPHXgl animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="WPHXgl"><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-SDAHhY","imgSrc":{"media":{"imageId":5778,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/satisfied-client-150x150.webp","orientation":"landscape"},"medium":{"height":140,"width":300,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/satisfied-client-300x140.webp","orientation":"landscape"},"full":{"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/satisfied-client.webp","height":221,"width":475,"orientation":"landscape"}}},"size":"full"},"altOriginal":"","captionOriginal":"","imgBorder":{"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal","delay":"500"},"hideMobile":true,"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]},"zIndex":{"Desktop":"10"},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"36"},"Tablet":{"unit":"%","point":"28"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":"5"}},"positioningRight":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"positioningTop":{"Desktop":{"unit":"%","point":"74"},"Tablet":{"unit":"%","point":""}},"positioningBottom":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-SDAHhY animated guten-element-hide desktop-fadeInDown hide-mobile"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/satisfied-client.webp" height="221" width="475"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/icon {"elementId":"guten-3GezEw","icon":"fab fa-facebook-f","iconColorOne":{"type":"variable","id":"white"},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"15"},"iconColorTwo":{"type":"variable","id":"theme-4"},"iconColorHoverOne":{"type":"variable","id":"white"},"iconColorHoverTwo":{"type":"variable","id":"theme-4"},"iconShape":"custom","iconBorderRadius":{"unit":"px","dimension":{"top":"14","right":"14","bottom":"14","left":"14"}},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal","delay":"500"},"hideMobile":true,"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"boxShadow":{"color":{"r":165,"g":62,"b":3,"a":0.1},"horizontal":"8","vertical":"11","blur":"47"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":"36"},"Tablet":{"unit":"%","point":"30"}},"positioningRight":{"Tablet":{"unit":"%","point":""}},"positioningTop":{"Desktop":{"unit":"%","point":"16"},"Tablet":{"unit":"%","point":"12"}},"positioningBottom":{"Tablet":{"unit":"%","point":""}}} -->
<div class="wp-block-gutenverse-icon guten-element guten-3GezEw guten-icon animated guten-element-hide desktop-fadeInDown hide-mobile"><span class="guten-icon-wrapper custom stacked"><i class="fab fa-facebook-f"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/icon {"elementId":"guten-H3v91W","icon":"fab fa-twitter","iconColorOne":{"type":"variable","id":"white"},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"15"},"iconColorTwo":{"type":"variable","id":"theme-3"},"iconColorHoverOne":{"type":"variable","id":"white"},"iconColorHoverTwo":{"type":"variable","id":"theme-3"},"iconShape":"custom","iconBorderRadius":{"unit":"px","dimension":{"top":"14","right":"14","bottom":"14","left":"14"}},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal","delay":"500"},"hideMobile":true,"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"boxShadow":{"color":{"r":165,"g":62,"b":3,"a":0.1},"horizontal":"8","vertical":"11","blur":"47","position":"outline"},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"flex-start"},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"positioningRight":{"Desktop":{"unit":"%","point":"14"},"Tablet":{"unit":"%","point":"28"}},"positioningTop":{"Desktop":{"unit":"%","point":"9"},"Tablet":{"unit":"%","point":"2"}},"positioningBottom":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}}} -->
<div class="wp-block-gutenverse-icon guten-element guten-H3v91W guten-icon animated guten-element-hide desktop-fadeInDown hide-mobile"><span class="guten-icon-wrapper custom stacked"><i class="fab fa-twitter"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/icon {"elementId":"guten-yzx5VK","icon":"gtn gtn-instagram-1-light","iconColorOne":{"type":"variable","id":"white"},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"15"},"iconColorTwo":{"type":"variable","id":"theme-9"},"iconColorHoverOne":{"type":"variable","id":"white"},"iconColorHoverTwo":{"type":"variable","id":"theme-9"},"iconShape":"custom","iconBorderRadius":{"unit":"px","dimension":{"top":"14","right":"14","bottom":"14","left":"14"}},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal","delay":"600"},"hideMobile":true,"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"boxShadow":{"color":{"r":165,"g":62,"b":3,"a":0.1},"horizontal":"8","vertical":"11","blur":"47","position":"outline"},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"flex-start"},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}},"positioningRight":{"Desktop":{"unit":"%","point":"9"},"Tablet":{"unit":"%","point":"26"}},"positioningTop":{"Desktop":{"unit":"%","point":"30"},"Tablet":{"unit":"%","point":"28"}},"positioningBottom":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}}} -->
<div class="wp-block-gutenverse-icon guten-element guten-yzx5VK guten-icon animated guten-element-hide desktop-fadeInDown hide-mobile"><span class="guten-icon-wrapper custom stacked"><i class="gtn gtn-instagram-1-light"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/image {"elementId":"guten-aQqoFZ","imgSrc":{"media":{"imageId":3946,"sizes":{"full":{"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/like-icon.webp","height":64,"width":68,"orientation":"landscape"}}},"size":"full"},"altOriginal":"","captionOriginal":"","imgBorder":{"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal","delay":"700"},"hideMobile":true,"margin":{"Desktop":[]},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"8"},"Tablet":{"unit":"%","point":"6"}},"positioningLocation":"absolute","positioningLeft":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":"24"}},"positioningRight":{"Tablet":{"unit":"%","point":""},"Desktop":{"unit":"%","point":"67"}},"positioningTop":{"Desktop":{"unit":"%","point":"33"},"Tablet":{"unit":"%","point":""}},"positioningBottom":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-aQqoFZ animated guten-element-hide desktop-fadeInDown hide-mobile"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/like-icon.webp" height="64" width="68"/></a></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/image {"elementId":"guten-wosvA6","imgSrc":{"media":{"imageId":3945,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/StockSnap_ZRNIM4IB6Ss-150x150.webp","orientation":"landscape"},"medium":{"height":300,"width":215,"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/StockSnap_ZRNIM4IB6Ss-215x300.webp","orientation":"portrait"},"full":{"url":"' . esc_url( SOCIATIC_URI ) . 'assets/img/StockSnap_ZRNIM4IB6Ss.webp","height":697,"width":500,"orientation":"portrait"}}},"size":"full"},"altOriginal":"","captionOriginal":"","width":{"Desktop":{"unit":"px","point":"400"},"Tablet":{"unit":"px","point":"380"},"Mobile":{"unit":"px","point":"175"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"align":{"Desktop":"center","Tablet":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-8","top":"","left":"100"}},"Tablet":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":[],"Tablet":[]}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-wosvA6"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/StockSnap_ZRNIM4IB6Ss.webp" height="697" width="500"/></a></div>
<!-- /wp:gutenverse/image --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
