<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sociatic Gutenverse Team', 'sociatic' ),
	'categories' => array( 'sociatic-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1190"},"gap":"no","elementId":"guten-hRuuSI","background":{"type":"default","color":{"type":"variable","id":"theme-11"}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":3899,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/team-about.webp"},"Tablet":{"id":3899,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/team-about.webp"},"Mobile":{"id":3899,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/team-about.webp"}},"position":{"Desktop":"center center"},"size":{"Desktop":"cover"},"repeat":{"Desktop":"no-repeat"}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"50","bottom":"50","right":"20","left":"20"}}}} -->
<div class="section-wrapper" data-id="hRuuSI"><section class="wp-block-gutenverse-section guten-element guten-section guten-hRuuSI layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null,"Tablet":null},"elementId":"guten-Bgwtmy","horizontalAlign":{"Desktop":"center","Tablet":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Bgwtmy"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Bgwtmy"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-khF1fp","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"oTRAFP","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"46","unit":"px"},"Mobile":{"point":"32","unit":"px"},"Tablet":{"point":"44","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"800"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"","left":"","top":"","bottom":""}},"Tablet":{"unit":"%","dimension":{"right":"12","left":"12","top":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"900","unit":"px"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-khF1fp animated guten-element-hide desktop-fadeInUp">The Creative Team Behind Sociatic</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-X6L5Ry","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"","left":"","top":"","bottom":""}},"Tablet":{"unit":"%","dimension":{"right":"8","left":"8"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"600","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-X6L5Ry animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet consectetur adipiscing elit semper dalar elementum tempus hac tellus libero accumsan dolor sit amet consctur.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1190"},"isChild":true,"gap":"no","elementId":"guten-amJav4","margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}}},"padding":{"Desktop":[]}} -->
<div class="section-wrapper" data-id="amJav4"><section class="wp-block-gutenverse-section guten-element guten-section guten-amJav4 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.3,"Tablet":null},"elementId":"guten-7qkS0k","margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-7qkS0k"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="7qkS0k"><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-wZQE66","profileType":"overlay","overlayType":"default","overlayPosition":"bottom","src":{"id":3900,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/team-1.webp"},"name":"","job":"","alignment":{"Desktop":"center"},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"profileBorder":{"radius":{"Desktop":[]}},"imageBorder":{"radius":{"Desktop":[]}},"imgHeight":{"Desktop":{"point":"","unit":"px"}},"hoverPadding":{"Desktop":[]},"hoverBgColor":{"r":0,"g":0,"b":0,"a":0.6},"hoverContentBorder":{"radius":{"Desktop":[]}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-wZQE66"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( SOCIATIC_URI ) . 'assets/img/team-1.webp" alt=""/><div class="profile-body bottom"><h3 class="profile-title "></h3><p class="profile-sub"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-gtNPlm","iconSize":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"gap":{"Desktop":"20"},"alignment":{"Desktop":"center"},"shape":"square","color":"custom","iconColor":{"type":"variable","id":"white"},"bgColor":{"type":"variable","id":"theme-6"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[]}},"itemPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"hoverIconColor":{"type":"variable","id":"white"},"hoverBgColor":{"type":"variable","id":"theme-0"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="guten-element guten-social-icons guten-gtNPlm square horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-oVrXp4"} -->
<div class="guten-element guten-social-icon guten-oVrXp4 facebook"><a id="guten-oVrXp4"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-59bFPb"} -->
<div class="guten-element guten-social-icon guten-59bFPb instagram"><a id="guten-59bFPb"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-Yna6n6"} -->
<div class="guten-element guten-social-icon guten-Yna6n6 link"><a id="guten-Yna6n6"><i class="gtn gtn-linkedin-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-zsvc8S","alignText":{"Mobile":"center"},"titleTag":"h4","text":"Hugo Baron","focusText":"","subText":"CEO and  Co-Founder","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-1"},"mainTypography":{"type":"variable","id":"ToWh5m","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"28","unit":"px"},"Tablet":{"point":"22","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1"}}},"mainMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"5"}},"Tablet":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"focusMargin":{"Desktop":[]},"focusPadding":{"Desktop":[]},"subColor":{"type":"variable","id":"theme-2"},"subTypography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"subMargin":{"Desktop":[],"Tablet":[]},"subPadding":{"Desktop":[],"Tablet":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"15"}},"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]}} -->
<div class="guten-element guten-advanced-heading guten-zsvc8S"><div class="heading-section "><h4 class="heading-title">Hugo Baron<span class="heading-focus"></span></h4></div><span class="heading-subtitle">CEO and  Co-Founder</span></div>
<!-- /wp:gutenverse/advanced-heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.3,"Tablet":null},"elementId":"guten-6j46YJ","margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","top":"20"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-6j46YJ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="6j46YJ"><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-GKN7jz","profileType":"overlay","overlayType":"default","overlayPosition":"bottom","src":{"id":3901,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/team-2.webp"},"name":"","job":"","alignment":{"Desktop":"center"},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"profileBorder":{"radius":{"Desktop":[]}},"hoverPadding":{"Desktop":[]},"hoverBgColor":{"r":0,"g":0,"b":0,"a":0.6},"hoverContentBorder":{"radius":{"Desktop":[]}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-GKN7jz"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( SOCIATIC_URI ) . 'assets/img/team-2.webp" alt=""/><div class="profile-body bottom"><h3 class="profile-title "></h3><p class="profile-sub"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-pnqP4Z","iconSize":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"gap":{"Desktop":"20"},"alignment":{"Desktop":"center"},"shape":"square","color":"custom","iconColor":{"type":"variable","id":"white"},"bgColor":{"type":"variable","id":"theme-6"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[]}},"itemPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"hoverIconColor":{"type":"variable","id":"white"},"hoverBgColor":{"type":"variable","id":"theme-0"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="guten-element guten-social-icons guten-pnqP4Z square horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-0OOc4z"} -->
<div class="guten-element guten-social-icon guten-0OOc4z facebook"><a id="guten-0OOc4z"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-jbmHcH"} -->
<div class="guten-element guten-social-icon guten-jbmHcH instagram"><a id="guten-jbmHcH"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-4ozoC6"} -->
<div class="guten-element guten-social-icon guten-4ozoC6 link"><a id="guten-4ozoC6"><i class="gtn gtn-linkedin-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-q3bA6Q","alignText":{"Mobile":"center"},"titleTag":"h4","text":"Lotte Willems","focusText":"","subText":"Chief of Marketing","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-1"},"mainTypography":{"type":"variable","id":"ToWh5m","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"28","unit":"px"},"Tablet":{"point":"22","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"mainMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"5"}},"Tablet":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"focusMargin":{"Desktop":[]},"focusPadding":{"Desktop":[]},"subColor":{"type":"variable","id":"theme-2"},"subTypography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"subMargin":{"Desktop":[],"Tablet":[]},"subPadding":{"Desktop":[],"Tablet":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"15"}},"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]}} -->
<div class="guten-element guten-advanced-heading guten-q3bA6Q"><div class="heading-section "><h4 class="heading-title">Lotte Willems<span class="heading-focus"></span></h4></div><span class="heading-subtitle">Chief of Marketing</span></div>
<!-- /wp:gutenverse/advanced-heading --></div></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.3,"Tablet":null},"elementId":"guten-kRf9UY","margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"20"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-kRf9UY"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="kRf9UY"><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-oAXpF2","profileType":"overlay","overlayType":"default","overlayPosition":"bottom","src":{"id":3902,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/team-3.webp"},"name":"","job":"","alignment":{"Desktop":"center"},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"profileBorder":{"radius":{"Desktop":[]}},"hoverPadding":{"Desktop":[]},"hoverBgColor":{"r":0,"g":0,"b":0,"a":0.6},"hoverContentBorder":{"radius":{"Desktop":[]}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-oAXpF2"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( SOCIATIC_URI ) . 'assets/img/team-3.webp" alt=""/><div class="profile-body bottom"><h3 class="profile-title "></h3><p class="profile-sub"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-wpsqfW","iconSize":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"gap":{"Desktop":"20"},"alignment":{"Desktop":"center"},"shape":"square","color":"custom","iconColor":{"type":"variable","id":"white"},"bgColor":{"type":"variable","id":"theme-6"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[]}},"itemPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"hoverIconColor":{"type":"variable","id":"white"},"hoverBgColor":{"type":"variable","id":"theme-0"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="guten-element guten-social-icons guten-wpsqfW square horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-0ajnvO"} -->
<div class="guten-element guten-social-icon guten-0ajnvO facebook"><a id="guten-0ajnvO"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-DHbB8j"} -->
<div class="guten-element guten-social-icon guten-DHbB8j instagram"><a id="guten-DHbB8j"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-EGjfOv"} -->
<div class="guten-element guten-social-icon guten-EGjfOv link"><a id="guten-EGjfOv"><i class="gtn gtn-linkedin-light"></i><span></span></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-ie2DKm","alignText":{"Mobile":"center"},"titleTag":"h4","text":"Austin Castro","focusText":"","subText":"Head of Sales","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-1"},"mainTypography":{"type":"variable","id":"ToWh5m","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"28","unit":"px"},"Tablet":{"point":"22","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"mainMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"5"}},"Tablet":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"focusMargin":{"Desktop":[]},"focusPadding":{"Desktop":[]},"subColor":{"type":"variable","id":"theme-2"},"subTypography":{"type":"variable","id":"a0sRlN","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"subMargin":{"Desktop":[],"Tablet":[]},"subPadding":{"Desktop":[],"Tablet":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"15"}},"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]}} -->
<div class="guten-element guten-advanced-heading guten-ie2DKm"><div class="heading-section "><h4 class="heading-title">Austin Castro<span class="heading-focus"></span></h4></div><span class="heading-subtitle">Head of Sales</span></div>
<!-- /wp:gutenverse/advanced-heading --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
