<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sociatic Gutenverse Brand Logo', 'sociatic' ),
	'categories' => array( 'sociatic-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1190"},"gap":"no","elementId":"guten-KX5HL4","margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","bottom":"20"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"50","bottom":"50"}},"Mobile":{"unit":"px","dimension":{"top":"30","bottom":"0"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":22.6,"Tablet":30},"elementId":"guten-p3yPbw","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"default","Mobile":"center"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-aNU9qy","content":"Some of brand we work with","textAlign":{"Mobile":"center","Tablet":"left"},"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-feature","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"800","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","bottom":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"right":"40"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":[]},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"227","unit":"px"}}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":77.4,"Tablet":70},"elementId":"guten-nsJ0tP","verticalAlign":{"Desktop":"center","Tablet":"center"}} -->
<!-- wp:gutenverse/logo-slider {"elementId":"guten-FJGTsU","logos":[{"title":"One","_key":"cUiwME","src":{"id":3814,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/financio.webp"},"imageLoad":"eager"},{"title":"Two","_key":"VV8lwF","src":{"id":3815,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/echelon.webp"},"imageLoad":"eager"},{"title":"Four","_key":"tM7z30","src":{"id":3816,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/nettiz.webp"},"imageLoad":"eager"},{"title":"Three","_key":"lDZVBQ","src":{"id":3817,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/zever.webp"},"imageLoad":"eager"}],"imageFixHeight":true,"imageHeight":{"Desktop":"86"},"imageFit":{"Desktop":"cover"},"imagePadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"20","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"imageMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"imageHoverPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"20","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"imageHoverMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"imageBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"imageBorderHover":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"spacing":{"Desktop":"0"},"itemShowed":{"Desktop":"4","Tablet":"3","Mobile":"2"},"autoplay":true,"loop":true,"arrowPadding":{"Desktop":[]},"arrowMargin":{"Desktop":[]},"arrowBorder":{"radius":{"Desktop":[]}},"opacity":"0.8","hoverOpacity":"1","margin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Mobile":[]}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
