<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sociatic Gutenverse Footer', 'sociatic' ),
	'categories' => array( 'sociatic-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1190"},"gap":"no","elementId":"guten-AahUF3","background":{"type":"default","color":{"type":"variable","id":"gv-color-text-primary"},"videoPlayOnMobile":false},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"40"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"50","bottom":"50"}}},"className":"#footer"} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-w0cGtK"} -->
<!-- wp:gutenverse/section {"width":{"Desktop":"1190"},"isChild":true,"gap":"no","elementId":"guten-FB4VCC","background":{"type":"default","color":"","videoPlayOnMobile":false},"margin":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":34.4,"Tablet":100},"elementId":"guten-NisvJG","verticalAlign":{"Desktop":"center"},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Tablet":[]}} -->
<!-- wp:gutenverse/image {"elementId":"guten-V5BZib","imgSrc":{"media":{"imageId":80,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/Logo-white.webp","orientation":"landscape"},"medium":{"height":69,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/Logo-white.webp","orientation":"landscape"},"large":{"height":234,"width":1024,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/Logo-white.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/Logo-white.webp","height":281,"width":1230,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"sociatic logo","captionOriginal":"","width":{"Desktop":{"unit":"px","point":""},"Mobile":{"unit":"px","point":""},"Tablet":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"","unit":"px"}},"url":"#","imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"align":{"Desktop":"left"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Tablet":{"unit":"%","point":"24"},"Desktop":{"unit":"%","point":"50"},"Mobile":{"unit":"%","point":"50"}},"ariaLabel":"sociatic logo","imageLoad":"lazy"} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-Q4W04x","textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"containsAnchorTag":false,"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"20","right":""}},"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"317","unit":"px"},"Tablet":{"unit":"%","point":"100"}}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/social-icons {"elementId":"guten-K0oA8G","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"16"},"alignment":{"Desktop":"flex-start"},"shape":"square","iconColor":{"type":"variable","id":"white"},"bgColor":{"type":"variable","id":"gv-color-accent"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"itemPadding":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"hoverIconColor":{"type":"variable","id":"gv-color-primary"},"hoverBgColor":{"type":"variable","id":"white"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]}} -->
<!-- wp:gutenverse/social-icon {"elementId":"guten-MgZQV8","url":"#","ariaLabel":"follow our facebook","icon":"gtn gtn-facebook-f","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0xOS4yNTQgMmMtMy45NDIgMC02LjI1NCAyLjA4Mi02LjI1NCA2LjgyNnY0LjE3NGgtNXY1aDV2MTJoNXYtMTJoNGwxLTVoLTV2LTMuMzI4YzAtMS43ODcgMC41ODMtMi42NzIgMi4yNi0yLjY3MmgyLjc0di00Ljc5NWMtMC40NzQtMC4wNjQtMS44NTUtMC4yMDUtMy43NDYtMC4yMDV6Ij48L3BhdGg+Cjwvc3ZnPgo=","text":"","iconSize":{"Desktop":{"unit":"px"}}} /-->

<!-- wp:gutenverse/social-icon {"elementId":"guten-BemfJl","url":"#","ariaLabel":"follow our instagram","icon":"fab fa-instagram","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTIyNC4xIDE0MWMtNjMuNiAwLTExNC45IDUxLjMtMTE0LjkgMTE0LjlzNTEuMyAxMTQuOSAxMTQuOSAxMTQuOVMzMzkgMzE5LjUgMzM5IDI1NS45IDI4Ny43IDE0MSAyMjQuMSAxNDF6bTAgMTg5LjZjLTQxLjEgMC03NC43LTMzLjUtNzQuNy03NC43czMzLjUtNzQuNyA3NC43LTc0LjcgNzQuNyAzMy41IDc0LjcgNzQuNy0zMy42IDc0LjctNzQuNyA3NC43em0xNDYuNC0xOTQuM2MwIDE0LjktMTIgMjYuOC0yNi44IDI2LjgtMTQuOSAwLTI2LjgtMTItMjYuOC0yNi44czEyLTI2LjggMjYuOC0yNi44IDI2LjggMTIgMjYuOCAyNi44em03Ni4xIDI3LjJjLTEuNy0zNS45LTkuOS02Ny43LTM2LjItOTMuOS0yNi4yLTI2LjItNTgtMzQuNC05My45LTM2LjItMzctMi4xLTE0Ny45LTIuMS0xODQuOSAwLTM1LjggMS43LTY3LjYgOS45LTkzLjkgMzYuMXMtMzQuNCA1OC0zNi4yIDkzLjljLTIuMSAzNy0yLjEgMTQ3LjkgMCAxODQuOSAxLjcgMzUuOSA5LjkgNjcuNyAzNi4yIDkzLjlzNTggMzQuNCA5My45IDM2LjJjMzcgMi4xIDE0Ny45IDIuMSAxODQuOSAwIDM1LjktMS43IDY3LjctOS45IDkzLjktMzYuMiAyNi4yLTI2LjIgMzQuNC01OCAzNi4yLTkzLjkgMi4xLTM3IDIuMS0xNDcuOCAwLTE4NC44ek0zOTguOCAzODhjLTcuOCAxOS42LTIyLjkgMzQuNy00Mi42IDQyLjYtMjkuNSAxMS43LTk5LjUgOS0xMzIuMSA5cy0xMDIuNyAyLjYtMTMyLjEtOWMtMTkuNi03LjgtMzQuNy0yMi45LTQyLjYtNDIuNi0xMS43LTI5LjUtOS05OS41LTktMTMyLjFzLTIuNi0xMDIuNyA5LTEzMi4xYzcuOC0xOS42IDIyLjktMzQuNyA0Mi42LTQyLjYgMjkuNS0xMS43IDk5LjUtOSAxMzIuMS05czEwMi43LTIuNiAxMzIuMSA5YzE5LjYgNy44IDM0LjcgMjIuOSA0Mi42IDQyLjYgMTEuNyAyOS41IDkgOTkuNSA5IDEzMi4xczIuNyAxMDIuNy05IDEzMi4xeiIvPjwvc3ZnPg==","text":"","iconSize":{"Desktop":{"unit":"px"}}} /-->

<!-- wp:gutenverse/social-icon {"elementId":"guten-UEOoQs","url":"#","ariaLabel":"follow our twitter","icon":"fab fa-x-twitter","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTM4OS4yIDQ4aDcwLjZMMzA1LjYgMjI0LjIgNDg3IDQ2NEgzNDVMMjMzLjcgMzE4LjYgMTA2LjUgNDY0SDM1LjhMMjAwLjcgMjc1LjUgMjYuOCA0OEgxNzIuNEwyNzIuOSAxODAuOSAzODkuMiA0OHpNMzY0LjQgNDIxLjhoMzkuMUwxNTEuMSA4OGgtNDJMMzY0LjQgNDIxLjh6Ii8+PC9zdmc+","text":"","iconSize":{"Desktop":{"unit":"px"}}} /-->

<!-- wp:gutenverse/social-icon {"elementId":"guten-22hdUN","url":"#","ariaLabel":"follow our linkedin","icon":"gtn gtn-linkedin-light","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0zLjg0NCAwLjQzOHEtMS41OTQgMC0yLjcxOSAxLjEyNXQtMS4xMjUgMi43MTkgMS4xMjUgMi43MTkgMi43MTkgMS4xMjUgMi43MTktMS4xMjUgMS4xMjUtMi43MTktMS4xMjUtMi43MTktMi43MTktMS4xMjV2MHpNMC41MzEgMTEuMDMxaDYuNjI1djIxLjM0NGgtNi42MjV2LTIxLjM0NHpNMjQuMDMxIDEwLjVxLTIuNDA2IDAtNCAxLjA5NHQtMi4yNSAyLjM0NGgtMC4wOTR2LTIuOTA2aC02LjM3NXYyMS4zNDRoNi42MjV2LTEwLjU2M3EwLTIuMDk0IDAuNzAzLTMuNzgxdDMuMjk3LTEuNjg4cTIuNTMxIDAgMi45ODQgMS44OTF0MC40NTMgMy43NjZ2MTAuMzc1aDYuNjI1di0xMS43MTlxMC0yLjE1Ni0wLjMxMy00LTAuMjgxLTEuODQ0LTEuMTQxLTMuMjE5dC0yLjQyMi0yLjE1Ni00LjA5NC0wLjc4MXYweiI+PC9wYXRoPgo8L3N2Zz4K","text":"","iconSize":{"Desktop":{"unit":"px"}}} /-->
<!-- /wp:gutenverse/social-icons -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":34.1,"Tablet":50},"elementId":"guten-0VMoAn","verticalAlign":{"Desktop":"center","Tablet":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"30"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<!-- wp:gutenverse/icon-list {"elementId":"guten-1VTsbg","spaceBetween":{"Desktop":"10"},"iconColor":{"type":"variable","id":"gv-color-accent"},"iconSize":{"Desktop":"15"},"textColor":{"type":"variable","id":"white"},"textIndent":{"Desktop":"10"},"textTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-Rwp0Ug","url":"#","hasGlobalLink":true,"ariaLabel":"email address","icon":"fas fa-envelope","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTQ4IDY0QzIxLjUgNjQgMCA4NS41IDAgMTEyYzAgMTUuMSA3LjEgMjkuMyAxOS4yIDM4LjRMMjM2LjggMzEzLjZjMTEuNCA4LjUgMjcgOC41IDM4LjQgMEw0OTIuOCAxNTAuNGMxMi4xLTkuMSAxOS4yLTIzLjMgMTkuMi0zOC40YzAtMjYuNS0yMS41LTQ4LTQ4LTQ4SDQ4ek0wIDE3NlYzODRjMCAzNS4zIDI4LjcgNjQgNjQgNjRINDQ4YzM1LjMgMCA2NC0yOC43IDY0LTY0VjE3NkwyOTQuNCAzMzkuMmMtMjIuOCAxNy4xLTU0IDE3LjEtNzYuOCAwTDAgMTc2eiIvPjwvc3ZnPg==","text":"contact@example.com"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-iXrhEO","url":"#","hasGlobalLink":true,"ariaLabel":"phone number","icon":"fas fa-phone","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTE2NC45IDI0LjZjLTcuNy0xOC42LTI4LTI4LjUtNDcuNC0yMy4ybC04OCAyNEMxMi4xIDMwLjIgMCA0NiAwIDY0QzAgMzExLjQgMjAwLjYgNTEyIDQ0OCA1MTJjMTggMCAzMy44LTEyLjEgMzguNi0yOS41bDI0LTg4YzUuMy0xOS40LTQuNi0zOS43LTIzLjItNDcuNGwtOTYtNDBjLTE2LjMtNi44LTM1LjItMi4xLTQ2LjMgMTEuNkwzMDQuNyAzNjhDMjM0LjMgMzM0LjcgMTc3LjMgMjc3LjcgMTQ0IDIwNy4zTDE5My4zIDE2N2MxMy43LTExLjIgMTguNC0zMCAxMS42LTQ2LjNsLTQwLTk2eiIvPjwvc3ZnPg==","text":"+62 4321-234-11"} /-->
<!-- /wp:gutenverse/icon-list -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":31.5,"Tablet":50},"elementId":"guten-rZ10h3","verticalAlign":{"Desktop":"center"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}},"Desktop":[]}} -->
<!-- wp:gutenverse/form-builder {"elementId":"guten-NuqsCM","formId":{"label":"Newsletter Form","value":1041},"successAlign":{"Desktop":null},"successPadding":{"Desktop":[]},"successBorder":{"radius":{"Desktop":[]}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"15"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/wrapper {"elementId":"guten-OAfs26","displayType":"flex","displayWidth":{"Desktop":{"unit":"px"}},"displayHeight":{"Desktop":{"unit":"px"}},"horizontalAlign":{"Desktop":"space-between","Tablet":false,"Mobile":false},"verticalAlign":{"Desktop":"center","Tablet":false,"Mobile":false},"background":{"type":"default","color":{"type":"variable","id":"gv-color-white"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"5","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"2","bottom":"2","right":"4"}}}} -->
<!-- wp:gutenverse/form-input-email {"elementId":"guten-Hi6mqo","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":[],"Mobile":[]},"labelMargin":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"58"},"Mobile":{"unit":"%","point":"50"}},"positioningLocation":"default","margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"inputPlaceholder":"Email Address","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"16","bottom":"16","right":"20","left":"10"}},"Mobile":[],"Tablet":[]},"inputMargin":{"Desktop":[],"Mobile":[]},"inputTypography":{"font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Mobile":{"point":"14","unit":"px"},"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":[]},"all":{"type":"none","width":null,"color":""}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"all":{"type":"none"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"all":{"type":"none"}},"inputBgColorNormal":{"Desktop":{"r":255,"g":255,"b":255,"a":0}},"inputBgColorHover":{"Desktop":{"r":255,"g":255,"b":255,"a":0}},"inputBgColorFocus":{"Desktop":{"r":255,"g":255,"b":255,"a":0}}} /-->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-CW6Lk0","content":"Get Started","buttonWidth":{"Mobile":"100","Tablet":""},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-primary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"positioningType":{"Desktop":"inline","Mobile":"inline","Tablet":"inline"},"positioningWidth":{"Tablet":{"unit":"%","point":"100"}},"positioningLocation":"default","positioningLeft":{"Desktop":{"point":"","unit":"px"},"Tablet":{"unit":"px","point":""},"Mobile":{"unit":"%","point":""}},"positioningRight":{"Desktop":{"unit":"%","point":"2"},"Mobile":{"unit":"%","point":"0"}},"positioningTop":{"Desktop":{"unit":"%","point":"11"},"Tablet":{"unit":"%","point":""},"Mobile":{"unit":"%","point":"120"}},"positioningBottom":{"Mobile":{"unit":"%","point":""},"Desktop":{"unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"color":{"type":"variable","id":"white"},"typography":{"font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"weight":"500","lineHeight":{"Desktop":{"unit":"em","point":""}},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"15","unit":"px"}}},"alignButton":{"Desktop":"flex-end","Mobile":"flex-start"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"28","left":"28"}},"Tablet":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}}}} /-->
<!-- /wp:gutenverse/wrapper -->
<!-- /wp:gutenverse/form-builder -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-AF6peW","margin":{"Desktop":{"unit":"px","dimension":{"top":"80"}},"Mobile":{"unit":"px","dimension":{"top":"100"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-Y8JKMA","margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}}} -->
<!-- wp:gutenverse/text-editor {"elementId":"guten-n4d6jo","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"left","Tablet":"left","Mobile":"center"},"textColor":{"type":"variable","id":"white"},"typography":{"font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"containsAnchorTag":true,"linkColor":{"type":"variable","id":"gv-color-accent"},"linkTypography":{"lineHeight":{"Desktop":{"unit":"px"}},"size":{"Desktop":{"unit":"px"}},"weight":"600"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Mobile":{"unit":"px","dimension":{"bottom":"0"}}}} -->
<!-- wp:paragraph -->
<p>Copyright © 2026 Built with <a href="https://gutenverse.com/?utm_source=sociatic&amp;utm_medium=footer" target="_blank" rel="noreferrer noopener">Gutenverse</a> Social Media Agency.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-07yIJV"} -->
<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-pB2up6"} -->
<!-- wp:gutenverse/column {"width":{"Desktop":70,"Tablet":60,"Mobile":null},"elementId":"guten-qDCEnG","margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}}} -->
<!-- wp:gutenverse/text-editor {"elementId":"guten-9ObXPy","alignment":{"Desktop":"right","Mobile":"center"},"textColor":{"type":"variable","id":"white"},"typography":{"font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"containsAnchorTag":true,"margin":{"Mobile":[],"Desktop":[]},"padding":{"Mobile":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Desktop":[]}} -->
<!-- wp:paragraph {"style":{"elements":{"link":{"color":{"text":"var:preset|color|white"}}}}} -->
<p class="has-link-color"><a href="#">Privacy Policy</a></p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":30,"Tablet":40,"Mobile":null},"elementId":"guten-Nox5DC","margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}}} -->
<!-- wp:gutenverse/text-editor {"elementId":"guten-xIjnRT","alignment":{"Desktop":"right","Mobile":"center"},"textColor":{"type":"variable","id":"white"},"typography":{"font":{"label":"Hind Siliguri","value":"Hind Siliguri","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"containsAnchorTag":true} -->
<!-- wp:paragraph {"style":{"elements":{"link":{"color":{"text":"var:preset|color|white"}}}}} -->
<p class="has-link-color"><a href="#">Terms and conditions</a></p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
