<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Sociatic Gutenverse Companies', 'sociatic' ),
	'categories' => array( 'sociatic-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1190"},"gap":"no","elementId":"guten-6B74nz","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"0","top":"100"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","top":"50","bottom":"0"}}}} -->
<div class="section-wrapper" data-id="6B74nz"><section class="wp-block-gutenverse-section guten-element guten-section guten-6B74nz layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-nQLPDc","horizontalAlign":{"Desktop":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-nQLPDc"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="nQLPDc"><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-deU8b1","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"oTRAFP","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"46","unit":"px"},"Mobile":{"point":"32","unit":"px"},"Tablet":{"point":"44","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"800"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"","left":"","top":"","bottom":""}},"Tablet":{"unit":"%","dimension":{"right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"900","unit":"px"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-deU8b1 animated guten-element-hide desktop-fadeInUp">Trusted By Companies Of All Size</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/logo-slider {"elementId":"guten-aAytDd","logos":[{"title":"One","_key":"fo2Fy3","src":{"id":3903,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/kavana.webp"}},{"title":"Two","_key":"TYFwmZ","src":{"id":3814,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/financio.webp"}},{"title":"Three","_key":"94DFE1","src":{"id":3904,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/hypebiz.webp"}},{"src":{"id":3815,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/echelon.webp"},"title":"Five","_key":"euChVe"},{"title":"Four","_key":"ktFCAi","src":{"id":3905,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/kavlaw.webp"}}],"imagePadding":{"Desktop":[]},"imageMargin":{"Desktop":[]},"imageBorder":{"radius":{"Desktop":[]}},"spacing":{"Desktop":"50","Tablet":"80","Mobile":"20"},"itemShowed":{"Desktop":"5","Tablet":"3","Mobile":"2"},"loop":true,"arrowPadding":{"Desktop":[]},"arrowMargin":{"Desktop":[]},"arrowBorder":{"radius":{"Desktop":[]}},"opacity":"1","margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<div class="guten-element guten-client-logo grid-desktop-3 guten-aAytDd animated guten-element-hide desktop-fadeInUp arrow-bottom-edge"><div class="client-list"><div id="guten-aAytDd" class="swiper-container" data-loop="true" data-autoplay="false" data-timeout="2400" data-nav="false" data-arrow="false" data-breakpoints="{&quot;0&quot;:{&quot;spaceBetween&quot;:20,&quot;slidesPerView&quot;:2},&quot;768&quot;:{&quot;spaceBetween&quot;:80,&quot;slidesPerView&quot;:3},&quot;1024&quot;:{&quot;spaceBetween&quot;:50,&quot;slidesPerView&quot;:5}}"><div class="swiper-wrapper"><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/kavana.webp" alt="One"/><img class="hover-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/kavana.webp" alt="One"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/financio.webp" alt="Two"/><img class="hover-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/financio.webp" alt="Two"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/hypebiz.webp" alt="Three"/><img class="hover-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/hypebiz.webp" alt="Three"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/echelon.webp" alt="Five"/><img class="hover-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/echelon.webp" alt="Five"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/kavlaw.webp" alt="Four"/><img class="hover-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/kavlaw.webp" alt="Four"/></div></div></div></div></div></div>
<!-- /wp:gutenverse/logo-slider -->

<!-- wp:gutenverse/logo-slider {"elementId":"guten-35lI0q","logos":[{"title":"Two","_key":"TYFwmZ","src":{"id":3906,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/xtreme.webp"},"hoverSrc":[]},{"title":"One","_key":"fo2Fy3","src":{"id":3816,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/nettiz.webp"},"hoverSrc":[]},{"title":"Three","_key":"94DFE1","src":{"id":3907,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/kness.webp"},"hoverSrc":[]},{"title":"Four","_key":"ktFCAi","src":{"id":3817,"image":"' . esc_url( SOCIATIC_URI ) . 'assets/img/zever.webp"},"hoverSrc":[]}],"imagePadding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"imageMargin":{"Desktop":[],"Mobile":[]},"imageHoverPadding":{"Mobile":[]},"imageHoverMargin":{"Mobile":[]},"imageBorder":{"radius":{"Desktop":[],"Mobile":[]}},"imageBorderHover":{"radius":{"Mobile":[]}},"spacing":{"Desktop":"50","Tablet":"80","Mobile":"20"},"itemShowed":{"Desktop":"4","Tablet":"2","Mobile":"1"},"loop":true,"arrowPadding":{"Desktop":[],"Mobile":[]},"arrowMargin":{"Desktop":[],"Mobile":[]},"arrowBorder":{"radius":{"Desktop":[],"Mobile":[]}},"opacity":"1","margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"60","left":"60"}},"Tablet":{"unit":"px","dimension":{"right":"120","left":"120"}},"Mobile":{"unit":"px","dimension":{"right":"100","left":"100"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"},"hideMobile":true} -->
<div class="guten-element guten-client-logo grid-desktop-3 guten-35lI0q animated guten-element-hide desktop-fadeInUp hide-mobile arrow-bottom-edge"><div class="client-list"><div id="guten-35lI0q" class="swiper-container" data-loop="true" data-autoplay="false" data-timeout="2400" data-nav="false" data-arrow="false" data-breakpoints="{&quot;0&quot;:{&quot;spaceBetween&quot;:20,&quot;slidesPerView&quot;:1},&quot;768&quot;:{&quot;spaceBetween&quot;:80,&quot;slidesPerView&quot;:2},&quot;1024&quot;:{&quot;spaceBetween&quot;:50,&quot;slidesPerView&quot;:4}}"><div class="swiper-wrapper"><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/xtreme.webp" alt="Two"/><img class="hover-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/xtreme.webp" alt="Two"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/nettiz.webp" alt="One"/><img class="hover-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/nettiz.webp" alt="One"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/kness.webp" alt="Three"/><img class="hover-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/kness.webp" alt="Three"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/zever.webp" alt="Four"/><img class="hover-image" src="' . esc_url( SOCIATIC_URI ) . 'assets/img/zever.webp" alt="Four"/></div></div></div></div></div></div>
<!-- /wp:gutenverse/logo-slider -->

<!-- wp:gutenverse/divider {"elementId":"guten-XYzV1g","width":{"Desktop":"30"},"dividerColor":{"r":235,"g":235,"b":235,"a":1},"size":{"Desktop":"1.5"},"gap":{"Desktop":"1","Mobile":""},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"50"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"","bottom":"0","left":""}},"Mobile":{"unit":"px","dimension":{"top":"30"}}}} -->
<div class="wp-block-gutenverse-divider guten-element guten-divider guten-XYzV1g"><div class="guten-divider-wrapper"><div class="guten-divider-default guten-divider-line guten-divider-regular"></div></div></div>
<!-- /wp:gutenverse/divider --></div></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
